import {
  REFRIGERATION_KNOWLEDGE,
  SYSTEM_DIAGNOSTICS_KNOWLEDGE,
  DEFROST_KNOWLEDGE,
  SPORLAN_KNOWLEDGE,
  COPELAND_KNOWLEDGE,
  HUSSMANN_KNOWLEDGE,
  DANFOSS_KNOWLEDGE,
  ARNEG_KNOWLEDGE,
  KEEPRITE_KNOWLEDGE,
  MATH_AND_ELECTRICAL_KNOWLEDGE,
  MICRO_THERMO_KNOWLEDGE,
  EVAPCO_LMP_KNOWLEDGE,
  PENN_CONTROLS_KNOWLEDGE,
  CARNOT_KNOWLEDGE,
  EMERSON_E2_E3_KNOWLEDGE,
  WALK_IN_KNOWLEDGE,
  PARALLEL_RACK_KNOWLEDGE,
  VFD_KNOWLEDGE,
  REFRIGERANT_RETROFIT_KNOWLEDGE,
  TYLER_HILL_PHOENIX_KNOWLEDGE,
  HEATCRAFT_BOHN_KNOWLEDGE,
  BITZER_KNOWLEDGE,
  LENNOX_RTU_KNOWLEDGE,
  CARRIER_RTU_KNOWLEDGE,
  YORK_RTU_KNOWLEDGE,
  TRANE_RTU_KNOWLEDGE,
  RTU_HVAC_DIAGNOSTICS_KNOWLEDGE,
  AAON_RTU_KNOWLEDGE,
  TRANE_RAUC_KNOWLEDGE,
  TEMPRITE_KNOWLEDGE,
  DIXELL_KNOWLEDGE,
  KYSOR_WARREN_KNOWLEDGE,
  HEAT_RECLAIM_KNOWLEDGE,
  FILTER_DRIER_KNOWLEDGE,
  SOLENOID_VALVE_KNOWLEDGE,
} from '@/lib/ai/prompts'

export interface KnowledgeTopic {
  slug: string
  title: string
  shortTitle: string
  description: string
  iconName: string           // lucide icon name (string, resolved in UI)
  colorClass: string         // e.g. 'blue' — used to build tailwind classes
  content: string            // full markdown string
  manualKeywords: string[]   // for DB search (ILIKE match on document title or manufacturer)
  tags: string[]
  category: 'manufacturer' | 'fundamentals' | 'hvac'
}

export const TOPICS: KnowledgeTopic[] = [
  {
    slug: 'refrigeration-fundamentals',
    title: 'Refrigeration Fundamentals',
    shortTitle: 'Fundamentals',
    description: 'CO₂ transcritical cycle, HFC basics, pressure-temperature relationships, oil management, superheat/subcooling, and system-level diagnostics.',
    iconName: 'Snowflake',
    colorClass: 'sky',
    content: REFRIGERATION_KNOWLEDGE,
    manualKeywords: ['refrigeration', 'fundamentals', 'basics', 'co2'],
    tags: ['CO₂', 'HFC', 'Basics'],
    category: 'fundamentals',
  },
  {
    slug: 'system-diagnostics',
    title: 'System Fault Diagnosis',
    shortTitle: 'Fault Diagnosis',
    description: 'Symptom-based fault finding for HFC multiplex racks and CO₂ transcritical boosters: high/low suction, head pressure, superheat, floodback, oil failure, compressor diagnostics, and a quick diagnosis matrix.',
    iconName: 'Activity',
    colorClass: 'red',
    content: SYSTEM_DIAGNOSTICS_KNOWLEDGE,
    manualKeywords: [],
    tags: ['Troubleshooting', 'HFC', 'CO₂', 'Compressors'],
    category: 'fundamentals',
  },
  {
    slug: 'defrost-systems',
    title: 'Defrost Systems',
    shortTitle: 'Defrost',
    description: 'Electric, hot gas (2-pipe and 3-pipe), and CO₂ off-cycle defrost: how each works, termination sensor placement, adaptive defrost, CO₂-specific considerations, and 12 common field mistakes.',
    iconName: 'Flame',
    colorClass: 'yellow',
    content: DEFROST_KNOWLEDGE,
    manualKeywords: [],
    tags: ['Defrost', 'Electric', 'Hot Gas', 'CO₂'],
    category: 'fundamentals',
  },
  {
    slug: 'sporlan',
    title: 'Sporlan',
    shortTitle: 'Sporlan',
    description: 'TXVs, EEVs, CDS/CDST stepper EPR valves, solenoids, filter-driers, electronic controls, and 12 common field mistakes.',
    iconName: 'Sliders',
    colorClass: 'blue',
    content: SPORLAN_KNOWLEDGE,
    manualKeywords: ['sporlan'],
    tags: ['Valves', 'EEV', 'TXV', 'Solenoids'],
    category: 'manufacturer',
  },
  {
    slug: 'copeland',
    title: 'Copeland / Emerson',
    shortTitle: 'Copeland',
    description: 'Scroll ZB/ZF compressors, Digital Scroll, Discus reciprocating, CoreSense diagnostics, ASTP, cylinder unloaders, and oil monitoring.',
    iconName: 'Zap',
    colorClass: 'violet',
    content: COPELAND_KNOWLEDGE,
    manualKeywords: ['copeland', 'coresense'],
    tags: ['Compressors', 'Scroll', 'Discus'],
    category: 'manufacturer',
  },
  {
    slug: 'hussmann',
    title: 'Hussmann',
    shortTitle: 'Hussmann',
    description: 'Display case families (RL/RLN/RM/FW), defrost types, KoolGas 2-pipe vs hot gas 3-pipe, DASH controller, parallel racks, Protocol systems, and CO₂.',
    iconName: 'LayoutGrid',
    colorClass: 'emerald',
    content: HUSSMANN_KNOWLEDGE,
    manualKeywords: ['hussmann'],
    tags: ['Cases', 'Racks', 'CO₂', 'KoolGas'],
    category: 'manufacturer',
  },
  {
    slug: 'danfoss',
    title: 'Danfoss',
    shortTitle: 'Danfoss',
    description: 'AK-SM store controllers, AK-PC pack controllers, AK-CC case controllers, CCMT/AKV EEVs, ICM/ICMTS/ICS valves, Booster CO₂ racks, and safety components.',
    iconName: 'Cpu',
    colorClass: 'rose',
    content: DANFOSS_KNOWLEDGE,
    manualKeywords: ['danfoss'],
    tags: ['Controls', 'CO₂', 'EEV', 'Valves'],
    category: 'manufacturer',
  },
  {
    slug: 'arneg',
    title: 'Arneg',
    shortTitle: 'Arneg',
    description: 'Oslo, Trinidad, Venice, Quebec, and Dakar case families, Dixell/Carel controllers, EC fan motors, CO₂ compatibility, and common case faults.',
    iconName: 'Store',
    colorClass: 'amber',
    content: ARNEG_KNOWLEDGE,
    manualKeywords: ['arneg'],
    tags: ['Cases', 'Dixell', 'Carel'],
    category: 'manufacturer',
  },
  {
    slug: 'keeprite',
    title: 'Keeprite',
    shortTitle: 'Keeprite',
    description: 'KLP/KLV unit cooler series, condensing units, walk-in cooler/freezer configurations, defrost systems, fan motors, refrigerant retrofits, and common faults.',
    iconName: 'Thermometer',
    colorClass: 'teal',
    content: KEEPRITE_KNOWLEDGE,
    manualKeywords: ['keeprite', 'keep-rite', 'klp', 'klv'],
    tags: ['Unit Coolers', 'Walk-In', 'Condensing Units'],
    category: 'manufacturer',
  },
  {
    slug: 'micro-thermo',
    title: 'Micro Thermo (MT-Alliance)',
    shortTitle: 'Micro Thermo',
    description: 'MT-Alliance platform boards (MT-500/700 series), LonWorks FTT10 network wiring, Case Controller EEV/relay outputs, pressure transducer selection, and controller fault diagnosis.',
    iconName: 'CircuitBoard',
    colorClass: 'purple',
    content: MICRO_THERMO_KNOWLEDGE,
    manualKeywords: ['microthermo', 'micro-thermo', 'micro thermo', 'mt-alliance', 'mt alliance', '70-mta', '74-mta', '100-50-10', '70-phw'],
    tags: ['Controls', 'LonWorks', 'Case Controllers'],
    category: 'manufacturer',
  },
  {
    slug: 'evapco-lmp',
    title: 'Evapco LMP',
    shortTitle: 'Evapco LMP',
    description: 'CO₂ transcritical booster rack systems: flash tank control, head pressure algorithm (sub/transcritical), hot gas defrost sequencing, MT superheat control, oil management, and CO₂ leak safety.',
    iconName: 'Gauge',
    colorClass: 'cyan',
    content: EVAPCO_LMP_KNOWLEDGE,
    manualKeywords: ['evapco', 'lmp', 'evapco lmp', 'systems lmp'],
    tags: ['CO₂', 'Transcritical', 'Racks', 'Booster'],
    category: 'manufacturer',
  },
  {
    slug: 'penn-controls',
    title: 'Penn Controls (Johnson Controls)',
    shortTitle: 'Penn Controls',
    description: 'A19 electromechanical temperature controls, A421 electronic digital controls, A28 two-stage controls, P70/P78 dual pressure controls, A99 NTC sensors, setpoint tables for R-404A/R-448A, and common field faults.',
    iconName: 'ToggleRight',
    colorClass: 'orange',
    content: PENN_CONTROLS_KNOWLEDGE,
    manualKeywords: ['penn', 'penn controls', 'a421', 'a19', 'p70', 'johnson controls'],
    tags: ['Temperature Controls', 'Pressure Controls', 'A421', 'P70'],
    category: 'manufacturer',
  },
  {
    slug: 'tyler-hill-phoenix',
    title: 'Tyler & Hill Phoenix',
    shortTitle: 'Tyler / Hill Phoenix',
    description: 'Tyler (Carrier) open multideck and reach-in case families, controllers, defrost wiring; Hill Phoenix display cases and the Advansor CO₂ transcritical booster rack system with Carel pCO5+ controls.',
    iconName: 'ShoppingBag',
    colorClass: 'slate',
    content: TYLER_HILL_PHOENIX_KNOWLEDGE,
    manualKeywords: ['tyler', 'hill phoenix', 'hillphoenix', 'advansor'],
    tags: ['Cases', 'CO₂', 'Advansor', 'Tyler'],
    category: 'manufacturer',
  },
  {
    slug: 'heatcraft-bohn',
    title: 'Heatcraft / Bohn / Larkin',
    shortTitle: 'Heatcraft / Bohn',
    description: 'Bohn, Larkin, and Climate Control unit cooler series, electric and hot gas defrost wiring, fan motor types, condensing unit selection, and 10 common field mistakes.',
    iconName: 'Warehouse',
    colorClass: 'pink',
    content: HEATCRAFT_BOHN_KNOWLEDGE,
    manualKeywords: ['heatcraft', 'bohn', 'larkin', 'climate control'],
    tags: ['Unit Coolers', 'Walk-In', 'Defrost', 'Bohn'],
    category: 'manufacturer',
  },
  {
    slug: 'bitzer',
    title: 'Bitzer Compressors',
    shortTitle: 'Bitzer',
    description: 'Ecoline semi-hermetic reciprocating, ORBIT scroll, CSH/CSS screw, and BSK/BSH CO₂ compressors; INT69 VS protection relay, IQ oil module, BITZER BEST software, tandem/trio configurations, and CO₂-specific requirements.',
    iconName: 'Settings2',
    colorClass: 'lime',
    content: BITZER_KNOWLEDGE,
    manualKeywords: ['bitzer'],
    tags: ['Compressors', 'CO₂', 'Ecoline', 'INT69'],
    category: 'manufacturer',
  },
  {
    slug: 'temprite',
    title: 'Temprite Oil Management',
    shortTitle: 'Temprite',
    description: 'Temprite oil separators (500, 600, 900, 300 series), oil reservoirs, mechanical and electronic (TraxOil) oil level controls — installation, sizing, element replacement, and rack oil management troubleshooting.',
    iconName: 'Layers',
    colorClass: 'orange',
    content: TEMPRITE_KNOWLEDGE,
    manualKeywords: ['temprite'],
    tags: ['Oil Separator', 'Oil Management', 'Rack', 'Temprite'],
    category: 'manufacturer',
  },
  {
    slug: 'carnot',
    title: 'Carnot (M&M Carnot / JCI)',
    shortTitle: 'Carnot',
    description: 'CO₂ transcritical booster rack systems (CAR-090, Aquilon DS), ejector-based flash gas recovery, GC outlet sensor installation, HP throttling control, commissioning checklist, and common fault diagnosis.',
    iconName: 'Wind',
    colorClass: 'cyan',
    content: CARNOT_KNOWLEDGE,
    manualKeywords: ['carnot'],
    tags: ['CO₂', 'Transcritical', 'Ejector', 'Booster'],
    category: 'manufacturer',
  },
  {
    slug: 'emerson-e2-e3',
    title: 'Emerson E2 / E3 Controllers',
    shortTitle: 'Emerson E2/E3',
    description: 'E2 and E3 supervisory store controllers, CPC (Computer Process Controls) I/O boards, MultiFlex boards, CC-100 case controllers, legacy CCBs, DIP switch addressing, LonWorks/Modbus networking, and E2→E3 upgrade guide.',
    iconName: 'Monitor',
    colorClass: 'green',
    content: EMERSON_E2_E3_KNOWLEDGE,
    manualKeywords: ['emerson e2', 'emerson e3', 'emerson supervisory', 'supervisory control e', 'cpc', 'multiflex', 'computer process controls', 'einstein'],
    tags: ['Store Controller', 'E2', 'E3', 'CPC', 'MultiFlex'],
    category: 'manufacturer',
  },
  {
    slug: 'vfd',
    title: 'Variable Frequency Drives (VFDs)',
    shortTitle: 'VFDs',
    description: 'VFD fundamentals for refrigeration, Danfoss FC102/FC103, ABB ACS550, and Yaskawa drives; condenser fan head pressure control, universal fault codes, parameter backup, and 10 common field mistakes.',
    iconName: 'Activity',
    colorClass: 'violet',
    content: VFD_KNOWLEDGE,
    manualKeywords: ['vfd', 'fc102', 'fc103', 'acs550', 'acs880', 'altivar', 'powerflex', 'yaskawa'],
    tags: ['VFD', 'Danfoss', 'ABB', 'Fan Control'],
    category: 'fundamentals',
  },
  {
    slug: 'refrigerant-retrofit',
    title: 'R-404A → R-448A / R-449A Retrofit',
    shortTitle: 'Refrigerant Retrofit',
    description: 'Step-by-step R-404A to R-448A (Solstice N-40) and R-449A (Opteon XP40) retrofit: oil assessment, filter-drier change, TXV bulb requirements, pressure setpoint tables, charging procedure, and 8 field mistakes to avoid.',
    iconName: 'RefreshCcw',
    colorClass: 'yellow',
    content: REFRIGERANT_RETROFIT_KNOWLEDGE,
    manualKeywords: ['r-448a', 'r-449a', 'n-40', 'xp40', 'opteon', 'solstice', 'retrofit'],
    tags: ['R-448A', 'R-449A', 'Retrofit', 'R-404A'],
    category: 'fundamentals',
  },
  {
    slug: 'math-electrical',
    title: 'Math & Electrical Reference',
    shortTitle: 'Math & Electrical',
    description: "Refrigeration calculations (superheat, subcooling, compression ratio, heat load, COP), electrical formulas (Ohm's law, 3-phase power, voltage drop, capacitor testing), and how to read ladder diagrams and wiring schematics.",
    iconName: 'Calculator',
    colorClass: 'indigo',
    content: MATH_AND_ELECTRICAL_KNOWLEDGE,
    manualKeywords: [],
    tags: ['Math', 'Electrical', 'Wiring Diagrams'],
    category: 'fundamentals',
  },
  {
    slug: 'walk-in-troubleshooting',
    title: 'Walk-In Cooler & Freezer Troubleshooting',
    shortTitle: 'Walk-In',
    description: 'Temperature not maintaining, unit cooler icing, drain problems, door and envelope issues, floor heater systems, airflow and fan motor diagnostics, and 10 common walk-in field mistakes.',
    iconName: 'Warehouse',
    colorClass: 'slate',
    content: WALK_IN_KNOWLEDGE,
    manualKeywords: [],
    tags: ['Walk-In', 'Cooler', 'Freezer', 'Troubleshooting'],
    category: 'fundamentals',
  },
  {
    slug: 'parallel-rack-systems',
    title: 'Parallel Rack Systems (HFC Multiplex)',
    shortTitle: 'Parallel Racks',
    description: 'HFC multiplex rack architecture, suction group staging, floating suction setpoints, oil management (separator, level controllers, equalization), head pressure control, common rack faults, refrigerant charge verification, and energy management features.',
    iconName: 'Layers',
    colorClass: 'pink',
    content: PARALLEL_RACK_KNOWLEDGE,
    manualKeywords: [],
    tags: ['Racks', 'HFC', 'Multiplex', 'Oil Management'],
    category: 'fundamentals',
  },
  {
    slug: 'lennox-rtu',
    title: 'Lennox Rooftop Units',
    shortTitle: 'Lennox RTU',
    description: 'LGH/LCH commercial RTUs, Prodigy 1 and 2 control boards, economizer (Interlink 102691-04 damper actuator), fault codes, ignition diagnostics, and common field failures.',
    iconName: 'Wind',
    colorClass: 'blue',
    content: LENNOX_RTU_KNOWLEDGE,
    manualKeywords: ['lennox', 'prodigy', 'lgh', 'lch', 'rooftop'],
    tags: ['Lennox', 'Prodigy', 'Economizer', 'RTU'],
    category: 'hvac',
  },
  {
    slug: 'carrier-rtu',
    title: 'Carrier Rooftop Units',
    shortTitle: 'Carrier RTU',
    description: '48TC/TM/TF and 50TJ/XC WeatherExpert commercial RTUs, ComfortLink II controls, economizer faults, refrigerant circuit, and maintenance.',
    iconName: 'Wind',
    colorClass: 'sky',
    content: CARRIER_RTU_KNOWLEDGE,
    manualKeywords: ['carrier', 'weatherexpert', 'comfortlink', 'bryant', 'rooftop'],
    tags: ['Carrier', 'WeatherExpert', 'ComfortLink', 'RTU'],
    category: 'hvac',
  },
  {
    slug: 'york-rtu',
    title: 'York Rooftop Units',
    shortTitle: 'York RTU',
    description: 'York / Johnson Controls Predator (ZJ/ZR) and Sunline RTUs, Quantum board diagnostics, economizer, compressor protection, and field faults.',
    iconName: 'Wind',
    colorClass: 'orange',
    content: YORK_RTU_KNOWLEDGE,
    manualKeywords: ['york', 'predator', 'sunline', 'quantum', 'rooftop', 'johnson controls'],
    tags: ['York', 'Predator', 'Quantum', 'RTU'],
    category: 'hvac',
  },
  {
    slug: 'trane-rtu',
    title: 'Trane Rooftop Units',
    shortTitle: 'Trane RTU',
    description: 'Trane Precedent (YCD/YCH/YSD/YSH) and Sintesis RTUs, ReliaTel controls (RTOM/RTRM), Tracer BAS, two-stage cooling, economizer fault codes.',
    iconName: 'Wind',
    colorClass: 'red',
    content: TRANE_RTU_KNOWLEDGE,
    manualKeywords: ['trane', 'precedent', 'reliattel', 'sintesis', 'voyager', 'rooftop'],
    tags: ['Trane', 'ReliaTel', 'Precedent', 'RTU'],
    category: 'hvac',
  },
  {
    slug: 'rtu-diagnostics',
    title: 'RTU Fault Diagnosis',
    shortTitle: 'RTU Diagnostics',
    description: 'Cross-manufacturer RTU troubleshooting: cooling and heating mode diagnosis, economizer operation, refrigerant charging, electrical checks, filter and airflow, seasonal startup.',
    iconName: 'Settings2',
    colorClass: 'slate',
    content: RTU_HVAC_DIAGNOSTICS_KNOWLEDGE,
    manualKeywords: [],
    tags: ['Troubleshooting', 'RTU', 'Economizer', 'HVAC'],
    category: 'hvac',
  },
  {
    slug: 'trane-rauc',
    title: 'Trane RAUC / RAUCC Condensing Units',
    shortTitle: 'Trane RAUCC',
    description: 'Trane RAUC and RAUCC commercial split-system air-cooled condensing units (20–60 ton), including RAUCC405BX03: dual-circuit scroll compressors, ReliaTel controls, refrigerant charging, tandem compressor service, condenser fan cycling, and common field faults.',
    iconName: 'Snowflake',
    colorClass: 'teal',
    content: TRANE_RAUC_KNOWLEDGE,
    manualKeywords: ['trane rauc', 'raucc', 'rauj', 'split system condensing'],
    tags: ['Trane', 'RAUCC', 'Condensing Unit', 'Split System'],
    category: 'hvac',
  },
  {
    slug: 'filter-driers',
    title: 'Filter-Drier Selection & Burnout Cleanup',
    shortTitle: 'Filter Driers',
    description: 'Filter-drier selection (Parker Sporlan Catch-All vs Henry Technologies), desiccant types (HH/XH cores), ARI sizing methodology, post-burnout cleanup protocol with acid test interpretation, and 8 common field mistakes.',
    iconName: 'Filter',
    colorClass: 'teal',
    content: FILTER_DRIER_KNOWLEDGE,
    manualKeywords: ['sporlan catch-all', 'henry filter', 'henry drier', 'catch-all', 'filter drier', 'desiccant', 'acid test', 'burnout'],
    tags: ['Filter Drier', 'Burnout', 'Acid Test', 'Henry', 'Sporlan'],
    category: 'fundamentals',
  },
  {
    slug: 'solenoid-valves',
    title: 'Solenoid Valve Troubleshooting',
    shortTitle: 'Solenoid Valves',
    description: 'Direct-acting vs pilot-operated solenoids, NC vs NO selection, coil testing (resistance + amperage), manual stem override procedure, voltage vs current diagnosis, common failure modes (stuck open/closed, chatter, coil burnout), and CO₂-rated valves.',
    iconName: 'Zap',
    colorClass: 'amber',
    content: SOLENOID_VALVE_KNOWLEDGE,
    manualKeywords: ['sporlan solenoid', 'danfoss evr', 'solenoid valve', 'liquid line solenoid', 'mkc coil', 'evra'],
    tags: ['Solenoid', 'Liquid Line', 'Coil Testing', 'Pilot-Operated', 'CO₂'],
    category: 'fundamentals',
  },
  {
    slug: 'heat-reclaim',
    title: 'Heat Reclaim Systems',
    shortTitle: 'Heat Reclaim',
    description: 'Supermarket heat reclaim fundamentals — desuperheaters, heat reclaim condensers, liquid subcoolers, CO₂ wet heat reclaim, head pressure control, diverting valves, water-side maintenance, control sequences, and fault diagnosis.',
    iconName: 'Flame',
    colorClass: 'rose',
    content: HEAT_RECLAIM_KNOWLEDGE,
    manualKeywords: ['heat reclaim', 'desuperheater', 'subcooler', 'heat recovery'],
    tags: ['Heat Reclaim', 'Desuperheater', 'Subcooler', 'CO₂', 'Energy'],
    category: 'fundamentals',
  },
  {
    slug: 'kysor-warren',
    title: 'Kysor Warren Display Cases',
    shortTitle: 'Kysor Warren',
    description: 'Kysor Warren supermarket display cases (EcoFlex multi-deck, C-Series coffin, G-Series glass door, service cases) — fan motors, anti-sweat heaters, defrost setup, drain systems, controllers, and common fault diagnosis.',
    iconName: 'ShoppingBag',
    colorClass: 'green',
    content: KYSOR_WARREN_KNOWLEDGE,
    manualKeywords: ['kysor warren', 'kysor', 'ecoflex', 'ecoshine'],
    tags: ['Display Cases', 'Kysor Warren', 'Daikin', 'MT/LT Cases'],
    category: 'manufacturer',
  },
  {
    slug: 'dixell',
    title: 'Dixell Controllers',
    shortTitle: 'Dixell',
    description: 'Dixell XR, XC, and XW series controllers for display cases, walk-in coolers, and condensing units — parameter programming, alarm/error codes, defrost setup, probe types, Modbus wiring, and troubleshooting.',
    iconName: 'Cpu',
    colorClass: 'indigo',
    content: DIXELL_KNOWLEDGE,
    manualKeywords: ['dixell', 'xr series', 'xc series', 'xw series', 'xr30c', 'xr40c'],
    tags: ['Case Controller', 'Dixell', 'XR', 'XC', 'Modbus'],
    category: 'manufacturer',
  },
  {
    slug: 'aaon-rtu',
    title: 'AAON / CES / Flo RTUs',
    shortTitle: 'AAON RTU',
    description: 'AAON RN and RQ series rooftop units (also sold as CES or Flo RTUs): MCS control system, fault codes, compressor staging, economizer, VFD fan systems, gas heat, and R-454B Next Gen models.',
    iconName: 'Wind',
    colorClass: 'cyan',
    content: AAON_RTU_KNOWLEDGE,
    manualKeywords: ['aaon', 'rn series', 'rq series', 'ces rtu', 'flo rtu'],
    tags: ['AAON', 'CES', 'Flo', 'MCS', 'RTU'],
    category: 'hvac',
  },
]

export function getTopicBySlug(slug: string): KnowledgeTopic | undefined {
  return TOPICS.find(t => t.slug === slug)
}
