import { test, expect } from '@playwright/test'
test('MT-CMP power, isolated tests, diagram and mystery exercise',async({page})=>{
 const errors:string[]=[]
 page.on('pageerror',e=>errors.push(e.message))
 await page.route('**/api/simulator/attempts',r=>r.fulfill({json:{ok:true}}))
 await page.goto('/simulation/micro-thermo-control')
 await expect(page.getByRole('heading',{name:'Trace the safety loop.'})).toBeVisible()
 await expect(page.locator('output')).toContainText('120 VAC')
 await page.getByRole('button',{name:'All power: ON',exact:true}).click()
 await page.getByLabel('Isolation setup').selectOption('loop')
 await page.getByLabel('Red probe',{exact:true}).selectOption('SL1')
 await page.getByLabel('Black probe',{exact:true}).selectOption('SL2')
 await expect(page.locator('output')).toContainText('OL')
 await page.getByLabel('Isolation setup').selectOption('oil')
 await page.getByLabel('Red probe',{exact:true}).selectOption('OIL-IN')
 await page.getByLabel('Black probe',{exact:true}).selectOption('OIL-OUT')
 await expect(page.locator('output')).toContainText('Continuity')
 await page.getByRole('button',{name:'Ladder / signal paths'}).click()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
 await page.getByRole('button',{name:'Controller + components'}).click()
 await page.screenshot({path:`/tmp/mt-trainer-${test.info().project.name}.png`,fullPage:true})
 await page.getByRole('button',{name:'Find the Fault',exact:true}).click()
 await expect(page.getByLabel('Condition',{exact:true})).toHaveCount(0)
 await expect(page.getByRole('button',{name:'Submit diagnosis'})).toBeVisible()
 expect(errors).toEqual([])
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
})
