const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const ts = require('typescript')
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, filename)
const { BITZER_FAULTS, bitzerState, bitzerReading } = require('../lib/simulation/bitzer-circuit.ts')
const volts = (f, a, b) => bitzerReading(f, true, 'V', 'none', a, b)
test('All injected faults release contactor; healthy coil still measures line voltage', () => {
  for (const fault of BITZER_FAULTS) assert.equal(bitzerState(fault.id).running, fault.id === 'none', fault.id)
  assert.equal(volts('none', 'A1', 'N'), '120 V')
  assert.equal(volts('coil', 'A1', 'N'), '120 V')
})
test('SE-B3 supply loss differs from hot PTC while both transfer the relay', () => {
  for (const f of ['mp-power', 'ptc-hot', 'ptc-open']) {
    assert.equal(volts(f, '11', '14'), '120 V')
    assert.equal(volts(f, '11', '12'), '0 V')
  }
  assert.equal(volts('mp-power', 'SE-L', 'SE-N'), '0 V')
  assert.equal(volts('ptc-hot', 'SE-L', 'SE-N'), '120 V')
  assert.match(volts('none', '12', 'N'), /Floating/)
})
test('Oil contacts and separately fed INT280 supply are independently diagnosable', () => {
  assert.equal(volts('oil-trip', '14', 'Oil-out'), '120 V')
  assert.equal(volts('oil-trip', 'Oil-L', 'Oil-N'), '120 V')
  assert.equal(volts('oil-power', 'Oil-L', 'Oil-N'), '0 V')
  assert.equal(volts('reg-trip', 'Oil-out', 'Reg-out'), '120 V')
  assert.equal(volts('reg-trip', 'Reg-L', 'Reg-N'), '230 V')
  assert.equal(volts('reg-power', 'Reg-L', 'Reg-N'), '0 V')
  assert.equal(volts('fuse', 'Reg-L', 'Reg-N'), '230 V')
  assert.match(volts('none', 'Reg-L', 'N'), /separate supply/)
})
test('Resistance requires de-energization and isolation, distinguishes open and hot PTC', () => {
  assert.match(bitzerReading('none', true, 'Ω', 'ptc', 'M1', 'M2'), /OFF/)
  assert.match(bitzerReading('none', false, 'Ω', 'none', 'M1', 'M2'), /Isolate/)
  assert.equal(bitzerReading('none', false, 'Ω', 'ptc', 'M1', 'M2'), '450 Ω')
  assert.equal(bitzerReading('ptc-hot', false, 'Ω', 'ptc', 'M1', 'M2'), '6000 Ω')
  assert.equal(bitzerReading('ptc-open', false, 'Ω', 'ptc', 'M1', 'M2'), 'OL')
  assert.equal(bitzerReading('coil', false, 'Ω', 'coil', 'N', 'A1'), 'OL')
  assert.equal(bitzerReading('none', false, 'Ω', 'coil', 'N', 'A1'), '180 Ω')
})
test('208 V variant uses line-to-line readings across all faults and preserves the separate regulator feed', () => {
  const read = (fault, a, b, power = true) => bitzerReading(fault, power, 'V', 'none', a, b, 208)
  for (const fault of BITZER_FAULTS) {
    const state = bitzerState(fault.id, true, 208)
    assert.equal(state.running, fault.id === 'none')
    assert.equal(read(fault.id, 'L1', 'N'), '208 V')
    assert.equal(read(fault.id, 'Reg-L', 'Reg-N'), fault.id === 'reg-power' ? '0 V' : '230 V')
    if (state.breakIndex >= 0) {
      const { CHAIN } = require('../lib/simulation/bitzer-circuit.ts')
      assert.equal(read(fault.id, CHAIN[state.breakIndex], CHAIN[state.breakIndex + 1]), '208 V', fault.id)
    }
    assert.equal(read(fault.id, 'L1', 'N', false), '0 V')
  }
  assert.equal(read('none', 'A1', 'N'), '208 V')
  assert.equal(read('coil', 'A1', 'N'), '208 V')
  assert.equal(read('hp', 'A1', 'N'), '0 V')
  assert.equal(read('none', 'SE-L', 'SE-N'), '208 V')
  assert.equal(read('oil-trip', 'Oil-L', 'Oil-N'), '208 V')
  assert.equal(read('oil-power', 'Oil-L', 'Oil-N'), '0 V')
  assert.match(read('none', 'Reg-L', 'N'), /separate supply/)
})
