'use client'
import { useState } from 'react'
import { saveSimAttempt } from '@/lib/simulation/attempts'
import { MT_FAULTS, MT_POINTS, MT_TESTS, mtState, mtReading, type MTSettings, type MTPoint, type MTFault, type MTIsolation } from '@/lib/simulation/micro-thermo-circuit'

const box = 'rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800'
const button = 'min-h-11 rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold dark:border-slate-600'
const select = 'min-h-11 min-w-0 rounded-lg border border-slate-300 bg-white px-2 text-sm dark:border-slate-600 dark:bg-slate-900'
const base = 'https://www.parker.com/content/dam/Parker-com/Literature/Sporlan/Sporlan-pdf-files/MicroThermo/'
export default function MicroThermoCircuitTrainer() {
  const [s,setS] = useState<MTSettings>({ fault:'hp', power:true, call:true, voltage:120, selector:'AUTO' })
  const [view,setView] = useState<'panel'|'ladder'>('panel')
  const [red,setRed] = useState<MTPoint>('FIELD-L'), [black,setBlack] = useState<MTPoint>('FIELD-R')
  const [probe,setProbe] = useState<'red'|'black'>('red'), [mode,setMode] = useState<'V'|'Ω'>('V')
  const [isolation,setIsolation] = useState<MTIsolation>('none')
  const [hidden,setHidden] = useState(false), [solved,setSolved] = useState(false), [guess,setGuess] = useState<MTFault>('hp')
  const [feedback,setFeedback] = useState(''), [errors,setErrors] = useState(0)
  const state=mtState(s), revealed=!hidden||solved
  function update(p:Partial<MTSettings>) { setS(prev=>({...prev,...p})) }
  function start(fault:MTFault,mystery=false) { setS({...s,fault,power:true,call:true,selector:'AUTO'});setHidden(mystery);setSolved(false);setFeedback('');setErrors(0);setIsolation('none');setMode('V') }
  function diagnose() {
    if(guess!==s.fault) { setErrors(e=>e+1);setFeedback('Keep testing. Compare the SL harness, each safety contact, supplies and proof circuit.');return }
    setSolved(true);setFeedback('Fault identified. Review the evidence and corrective action below.')
    saveSimAttempt({rack:'safety-circuit',scenarioId:`mt-cmp-${s.voltage}-${s.fault}`,scenarioName:`MT-CMP: ${MT_FAULTS.find(f=>f.id===s.fault)!.name}`,mode:'wiring',score:Math.max(0,100-errors*15),correct:1,total:1,falsePositives:errors})
  }
  function terminal(p:MTPoint) { return <button key={p} aria-label={`Test point ${p}`} onClick={()=>probe==='red'?setRed(p):setBlack(p)} className={`flex min-h-11 items-center gap-1 rounded-lg border px-2 py-2 text-[10px] font-mono ${red===p?'border-red-400 bg-red-950 text-white':black===p?'border-sky-300 bg-slate-700 text-white':'border-emerald-700 bg-emerald-950 text-emerald-100'}`}><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-slate-300 text-slate-900">−</span>{p}{red===p?' • R':''}{black===p?' • B':''}</button> }
  const lamp=(label:string,on:boolean,color='bg-emerald-400')=><div key={label} className="flex items-center justify-between gap-4 text-xs"><span>{label}</span><span aria-label={`${label} ${on?'on':'off'}`} className={`h-3 w-3 rounded-full ${on?`${color} shadow-[0_0_9px_currentColor]`:'bg-slate-950 ring-1 ring-white/20'}`} /></div>
  return <div className="space-y-4 text-slate-800 dark:text-slate-100">
    <header className="overflow-hidden rounded-2xl bg-gradient-to-br from-slate-950 via-indigo-950 to-slate-900 p-5 text-white sm:p-7">
      <p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-200">Micro Thermo · MT-CMP / 9XX-632F</p>
      <h1 className="mt-3 text-3xl font-bold">Trace the safety loop.</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-300">An SLA call starts with evidence. Check power, separate safety from proof, and find the open contact with your meter.</p>
      <div className="mt-5 flex flex-wrap gap-2 text-xs">{['Photo-inspired controller','A-104 external circuit','Two-probe troubleshooting'].map(t=><span key={t} className="rounded-md border border-white/15 bg-white/5 px-3 py-2">{t}</span>)}</div>
    </header>
    <section className={`${box} flex flex-wrap items-end gap-3`} aria-label="Exercise setup">
      <button className={button} onClick={()=>start('hp')} aria-pressed={!hidden}>Practice</button><button className={`${button} bg-indigo-600 text-white`} onClick={()=>start(MT_FAULTS[1+Math.floor(Math.random()*(MT_FAULTS.length-1))].id,true)}>Find the Fault</button>
      {!hidden&&<label className="grid min-w-0 flex-1 gap-1 text-xs">Condition<select className={select} value={s.fault} onChange={e=>start(e.target.value as MTFault)}>{MT_FAULTS.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}
      <label className="grid gap-1 text-xs">Field supply<select className={select} value={s.voltage} onChange={e=>update({voltage:Number(e.target.value) as 120|208})}><option value={120}>120 V · L–N</option><option value={208}>208 V · L1–L2</option></select></label>
    </section>
    <div className={`${box} flex flex-wrap gap-2`}>
      <button className={button} onClick={()=>{update({power:!s.power});setIsolation('none');setMode('V')}}>All power: {s.power?'ON':'ISOLATED'}</button>
      <button className={button} onClick={()=>update({call:!s.call})}>Call: {s.call?'ON':'OFF'}</button>
      <button className={button} onClick={()=>update({selector:s.selector==='AUTO'?'OFF':'AUTO'})}>Selector: {s.selector}</button>
      <p className="w-full text-xs text-slate-500 dark:text-slate-400">Settled training states; actual alarm names, delays, latching and MAN ON behavior require the site configuration. No bypass or reset is simulated.</p>
    </div>
    <section className="safe-top sticky top-0 z-20 rounded-xl bg-slate-950 p-4 text-white shadow-lg" aria-label="Multimeter">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-widest text-slate-400">{mode==='V'?'AC voltage':'Isolated continuity'} · {red} / {black}</p><output className="mt-1 block font-mono text-lg text-emerald-300" aria-live="polite">{mtReading(s,mode,isolation,red,black)}</output></div><div className="flex flex-wrap gap-2">{(['red','black'] as const).map(p=><button key={p} className={`${button} ${probe===p?'bg-slate-700':''}`} aria-pressed={probe===p} onClick={()=>setProbe(p)}>{p==='red'?'Red':'Black'} probe</button>)}<button className={button} onClick={()=>setMode(mode==='V'?'Ω':'V')}>Mode: {mode}</button></div></div>
    </section>
    <section className={`${box} grid gap-3 sm:grid-cols-3`}>
      {(['Red','Black'] as const).map(p=><label key={p} className="grid gap-1 text-xs">{p} probe<select className={select} value={p==='Red'?red:black} onChange={e=>p==='Red'?setRed(e.target.value as MTPoint):setBlack(e.target.value as MTPoint)}>{MT_POINTS.map(t=><option key={t}>{t}</option>)}</select></label>)}
      <label className="grid gap-1 text-xs">Isolation setup<select className={select} disabled={s.power} value={isolation} onChange={e=>{setIsolation(e.target.value as MTIsolation);setMode(e.target.value==='none'?'V':'Ω')}}>{Object.entries(MT_TESTS).map(([id,t])=><option key={id} value={id}>{t.label}</option>)}</select></label>
      <p className="text-xs text-slate-500 dark:text-slate-400 sm:col-span-3">Power off and verify absence of voltage before disconnecting conductors. In isolated mode, SL/LPS/PROOF points represent the external harness, not the controller pins. Reconnect before applying power.</p>
    </section>
    <div className="flex gap-2">{(['panel','ladder'] as const).map(v=><button key={v} className={`${button} ${view===v?'bg-indigo-600 text-white':''}`} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='panel'?'Controller + components':'Ladder / signal paths'}</button>)}</div>
    {view==='panel'?<section className="grid gap-4 rounded-2xl border border-slate-700 bg-slate-900 p-4 text-white md:grid-cols-[250px_1fr]">
      <div className="mx-auto w-full max-w-[280px] rounded-xl border-4 border-slate-600 bg-gradient-to-r from-indigo-950 to-indigo-900 p-4 shadow-xl">
        <div className="flex justify-between text-[10px] tracking-widest text-indigo-200"><span>MICRO THERMO</span><span>C1</span></div>
        <div className="mt-5 space-y-3">{lamp('Power',state.logic)}<p className="text-[10px] text-indigo-200">STATUS / COMMAND · training indications</p>{lamp('Auto',state.logic&&s.selector==='AUTO','bg-red-400')}{lamp('Proof',state.proof)}{lamp('Alarm',state.logic&&(!state.sl||!state.lp||(state.command&&!state.proof)),'bg-red-400')}{lamp('Run',state.command,'bg-red-400')}</div>
        <div className="mt-5 space-y-4">{([['PROOF IN','PROOF1','PROOF2'],['LPS IN','LPS1','LPS2'],['SL IN','SL1','SL2'],['COMPRESSOR OUT','COMP1','COMP2']] as const).map(([label,a,b])=><div key={label}><p className="mb-1 text-[10px] tracking-widest text-indigo-200">{label}</p><div className="grid grid-cols-2 gap-1">{terminal(a)}{terminal(b)}</div></div>)}</div>
        <div className="my-5 rounded border border-white/20 bg-black/30 p-3 text-center font-mono text-sm">AUTO / OFF <span className="text-indigo-300">· MAN ON*</span></div>{lamp('Field Power',state.field)}<p className="mt-3 text-[10px] text-indigo-200">*MAN ON shown for identification only.</p>
      </div>
      <div className="space-y-4"><div className="rounded-xl border border-slate-600 bg-slate-800 p-4"><p className="text-xs uppercase tracking-widest text-indigo-200">Observed operation</p><h2 className="mt-2 text-xl font-bold">{isolation==='none'?state.status:'External test circuit isolated'}</h2><p className="mt-2 text-sm text-slate-300">Contactor: {isolation!=='none'?'test setup':state.output?'pulled in':'released'} · Proof: {state.proof?'present':'absent'}</p></div>
        <div className="grid gap-3 sm:grid-cols-2">{([['Field supply','L and N/L2 · never assume ground is return','FIELD-L','FIELD-R'],['Logic supply','24 VAC across L1–L2 · center-tapped supply','LOGIC-L1','LOGIC-L2'],['High-pressure control','External series contact · terminal names are training labels','HP-IN','HP-OUT'],['Oil safety control','Safety contact only · separate oil-control diagnostics','OIL-IN','OIL-OUT']] as const).map(([name,note,a,b])=><div key={name} className="rounded-xl border border-slate-600 bg-gradient-to-br from-slate-700 to-slate-800 p-4"><div className="mb-4 h-1 w-8 rounded bg-amber-400"/><h3 className="font-semibold">{name}</h3><p className="mb-4 mt-1 text-xs leading-relaxed text-slate-300">{note}</p><div className="flex flex-wrap gap-2">{terminal(a)}{terminal(b)}</div></div>)}</div>
        <p className="text-xs leading-relaxed text-slate-400">Faceplate follows your photos; component blocks show functional test points, not manufacturer terminal assignments. The external SL path is HPC → oil safety → return. A-104 also includes the separate LPC, time-delay/current-sensing and proof circuitry; their timing is outside this model.</p>
      </div>
    </section>:<section className={`${box} space-y-5`}><h2 className="font-bold">Separate circuits. Separate evidence.</h2><p className="text-sm text-slate-500 dark:text-slate-400">Simplified connection view derived from A-104. Lines show connectivity, not live voltage. Use the full drawing for installation.</p>
      <div className="overflow-x-auto rounded-xl bg-slate-950 p-4 text-white"><div className="min-w-[560px] space-y-6">
        <div><p className="mb-2 text-xs text-indigo-200">SL EXTERNAL HARNESS · isolate to test</p><div className="flex items-center">{terminal('SL1')}<span className="h-px flex-1 bg-amber-400"/><div className="rounded border border-slate-500 p-2"><p className="mb-2 text-center text-xs">HPC contact</p><div className="flex gap-1">{terminal('HP-IN')}{terminal('HP-OUT')}</div></div><span className="h-px flex-1 bg-amber-400"/><div className="rounded border border-slate-500 p-2"><p className="mb-2 text-center text-xs">Oil safety</p><div className="flex gap-1">{terminal('OIL-IN')}{terminal('OIL-OUT')}</div></div><span className="h-px flex-1 bg-amber-400"/>{terminal('SL2')}</div></div>
        {([['LOW PRESSURE','LPS1','LPC contact','LPS2'],['RUNNING PROOF','PROOF1','Proof relay contact','PROOF2'],['COMPRESSOR LOAD','COMP1','Contactor coil + proof relay','COMP2']] as const).map(([name,a,label,b])=><div key={name}><p className="mb-2 text-xs text-indigo-200">{name}</p><div className="flex items-center">{terminal(a)}<span className="h-px flex-1 bg-slate-400"/><span className="rounded border border-slate-500 px-4 py-3 text-xs">{label}</span><span className="h-px flex-1 bg-slate-400"/>{terminal(b)}</div></div>)}
      </div></div></section>}
    {hidden&&!solved&&<section className={`${box} flex flex-wrap items-end gap-3`}><label className="grid min-w-0 flex-1 gap-1 text-xs">Your diagnosis<select className={select} value={guess} onChange={e=>setGuess(e.target.value as MTFault)}>{MT_FAULTS.filter(f=>f.id!=='none').map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button className={`${button} bg-indigo-600 text-white`} onClick={diagnose}>Submit diagnosis</button></section>}
    {feedback&&<p role="status" className={box}>{feedback}</p>}
    {revealed&&<section className={`${box} border-l-4 border-l-indigo-500`}><h2 className="font-bold">{MT_FAULTS.find(f=>f.id===s.fault)!.name}</h2><p className="mt-2 text-sm">{MT_FAULTS.find(f=>f.id===s.fault)!.detail}</p></section>}
    <details className={box}><summary className="min-h-11 cursor-pointer font-bold">SLA troubleshooting · what to test next</summary><ol className="ml-5 list-decimal space-y-3 text-sm"><li>Record the exact alarm, selector position, Power / Field Power / Run / Proof indications and compressor behavior.</li><li>Check field supply across FIELD-L / FIELD-R and logic supply across LOGIC-L1 / LOGIC-L2. A lit logic Power LED does not establish field power.</li><li>For the SL exercise: isolate all power, verify dead, disconnect the external SL harness and test SL1–SL2. OL identifies an open external path, not which device opened.</li><li>Isolate and test HPC and oil safety contacts individually. If both close, check the conductors and terminations. This exercise includes an open return wire.</li><li>If SL is intact, distinguish LPS from proof. A contactor that runs without proof directs you to the proof circuit. Command without coil voltage directs you to supply/output checks.</li><li>Correct the underlying cause, reconnect and follow the actual controller and safety-device reset procedures. Never bridge a safety to keep the compressor running.</li></ol></details>
    <details className={box}><summary className="min-h-11 cursor-pointer font-bold">Manufacturer references + model limits</summary><div className="space-y-3 text-sm"><p>C-008 Rev 3 lists dry-contact digital inputs, a 24 VAC center-tapped supply and separate field power. Your photo marks the inputs 120/208/240 VAC. This revision/application difference is unresolved: live input readings and internal board circuitry are deliberately not synthesized.</p><p>SLA is used here as the requested safety-line-open exercise, not a verified firmware alarm definition. Alarm delay, latching, exact LEDs and manual operation must be confirmed with the installed software and rack schematic. Logic and field supplies are independently faultable; all-power isolation represents both being made safe.</p><p>Voltage is modeled only across field supply, the full 24 VAC logic winding and the compressor load. Isolated continuity is qualitative; ghost voltages, internal sensing and coil ohms are not modeled. The oil control, LPC and proof contact must be checked under their appropriate operating/test conditions.</p><ul className="list-inside list-disc space-y-2"><li><a className="text-blue-600 underline dark:text-blue-400" href="https://www.parker.com/literature/Sporlan/Sporlan%20pdf%20files/MicroThermo/C-008%20MT-CMP%20rev3.pdf" target="_blank" rel="noreferrer">C-008 Rev 3 · MT-CMP controller specification / terminal layout</a></li><li><a className="text-blue-600 underline dark:text-blue-400" href={`${base}A-104-COMP-CTRL-DIAG-2-rev5.pdf`} target="_blank" rel="noreferrer">A-104 Rev 5 · HPC + oil safety (this trainer’s reference)</a></li><li><a className="text-blue-600 underline dark:text-blue-400" href={`${base}A-108-COMP-CTRL-DIAG-6-rev4.pdf`} target="_blank" rel="noreferrer">A-108 Rev 4 · solid-state module + Demand Cooling variant</a></li></ul><p>To match a specific rack: provide its electrical diagram, MT-CMP part/revision label, oil/motor protection models and an Alliance screenshot of the SLA alarm/configuration.</p></div></details>
  </div>
}
