import type { FaultDef, SystemKey } from './types'

export const SYSTEM_META: Record<SystemKey, { label: string; short: string }> = {
  refrigeration: { label: 'Refrigeration', short: 'REF' },
  electrical:    { label: 'Electrical',    short: 'ELEC' },
  plumbing:      { label: 'Plumbing',      short: 'PLMB' },
  hvac:          { label: 'HVAC',          short: 'HVAC' },
}

const LOTO_CHECK = { id: 'loto', label: 'Lock out / tag out the circuit', tool: 'Lock & tag', minutes: 5, finding: 'Breaker locked open, tag hung, verified dead with the meter. Safe to open the panel.' }

export const FAULTS: FaultDef[] = [
  // ── Refrigeration ──────────────────────────────────────────────────────────
  {
    id: 'dt_failed_open',
    system: 'refrigeration',
    kinds: ['reach-in-freezer'],
    title: 'Doors fogged, product going soft',
    report: 'Frozen department says the doors on this run have been sweating since yesterday and the ice cream is soft on the top shelf.',
    cue: 'Every door on the run is fogged. Through the glass you can see frost bridged across the whole coil face. Fans are running hard.',
    readings: [
      { key: 'caseT', label: 'Discharge air', value: 4, unit: '°F', jitter: 0.6, wander: 1, status: 'crit', expect: '−12 °F' },
      { key: 'suct', label: 'Suction at case', value: 6.1, unit: 'psig', decimals: 1, jitter: 0.25, wander: 0.4, status: 'warn', expect: '≈ 8.5 psig (−22 °F SST, R-448A)' },
      { key: 'sh', label: 'Superheat', value: 3, unit: '°F', jitter: 0.4, status: 'warn', expect: '8–10 °F' },
      { key: 'frost', label: 'Coil frost', value: 92, unit: '%', jitter: 0, status: 'crit', expect: '< 30 %' },
    ],
    checks: [
      { id: 'log', label: 'Pull the controller defrost log', tool: 'Case controller', minutes: 8, key: true, finding: 'Defrost initiates every 6 h on schedule — but every cycle terminates in under a minute. It never gets a chance to melt anything.' },
      { id: 'dt', label: 'Meter the DT switch with the coil cold', tool: 'Multimeter (Ω)', minutes: 10, key: true, finding: 'Reads OPEN at a −5 °F coil. A termination switch should be CLOSED below 55 °F — this one has failed open.' },
      { id: 'sight', label: 'Check the sight glass at the rack', tool: 'Eyes', minutes: 12, finding: 'Clear, no bubbles. Liquid supply looks fine.' },
      { id: 'gasket', label: 'Walk the door gaskets', tool: 'Hands', minutes: 6, finding: 'All gaskets seal — a dollar bill drags on every door. Not the doors.' },
    ],
    causes: [
      { id: 'dt', label: 'Defrost termination switch failed open', correct: true, why: 'The log shows defrost starting and instantly ending; an open DT tells the controller "coil is warm, stop" the moment defrost begins. No melt, ice builds all week.' },
      { id: 'charge', label: 'Low refrigerant charge', why: 'A low charge gives you HIGH superheat and a starved coil. This coil has low superheat and a clear sight glass — it is choked with ice, not starved.' },
      { id: 'gasket', label: 'Door gasket leaking', why: 'Bad gaskets add load and frost, but would not make defrost terminate in under a minute. The log rules this out.' },
      { id: 'fan', label: 'Evaporator fan motor failed', why: 'Fans are audibly running and pulling air. A dead fan would show as no discharge air, not a fogged coil with airflow.' },
    ],
    fixes: [
      { id: 'dt', label: 'Replace the DT switch, force a manual defrost, verify termination on temp', correct: true, why: 'New switch reads closed on a cold coil, opens near 55 °F. Manual defrost clears the coil in ~35 min and the case pulls back to −12 °F.' },
      { id: 'charge', label: 'Add refrigerant', why: 'Nothing is wrong with the charge. You would overcharge the circuit and the coil would still be a block of ice.' },
      { id: 'timer', label: 'Shorten the defrost interval to every 4 h', why: 'More defrosts that each end in a minute still melt nothing. You have to fix why it terminates.' },
      { id: 'scrape', label: 'Scrape the ice off and leave it', why: 'It will be iced again by tomorrow. The termination switch is still open.' },
    ],
    shrinkPerMin: 4,
    complaintAfterMin: 90,
    knowledge: [{ slug: 'defrost-systems', label: 'Defrost Systems' }, { slug: 'system-diagnostics', label: 'System Diagnostics' }],
  },
  {
    id: 'txv_starved',
    system: 'refrigeration',
    kinds: ['dairy-case', 'meat-case'],
    title: 'Case warm, milk at 44 °F',
    report: 'Manager pulled a thermometer on the milk — 44 °F. The rest of the dairy line is fine.',
    cue: 'Fans are strong and the coil is clean, but only the first pass or so is frosted. The rest of the coil is dry and warm.',
    readings: [
      { key: 'dis', label: 'Discharge air', value: 38, unit: '°F', jitter: 0.5, wander: 0.8, status: 'crit', expect: '28–30 °F' },
      { key: 'suct', label: 'Suction at case', value: 44, unit: 'psig', decimals: 1, jitter: 0.4, wander: 0.6, status: 'warn', expect: '≈ 53 psig (+18 °F SST, R-404A)' },
      { key: 'sh', label: 'Superheat', value: 28, unit: '°F', jitter: 0.6, status: 'crit', expect: '8–10 °F' },
      { key: 'liq', label: 'Liquid pressure at rack', value: 195, unit: 'psig', jitter: 0.8, status: 'ok', expect: '≈ 195 psig' },
    ],
    checks: [
      { id: 'strainer', label: 'Feel for a temperature drop across the liquid strainer', tool: 'Hands / IR gun', minutes: 6, key: true, finding: 'Inlet and outlet of the strainer read the same, 88 °F. No restriction upstream of the valve.' },
      { id: 'bulb', label: 'Inspect the TXV sensing bulb', tool: 'Eyes', minutes: 5, key: true, finding: 'Bulb is strapped tight and insulated on the suction line. Capillary looks intact — but the head does not respond when you warm the bulb in your hand.' },
      { id: 'sight', label: 'Check the sight glass at the rack', tool: 'Eyes', minutes: 12, finding: 'Clear and full. Other cases on the line run normally.' },
      { id: 'doors', label: 'Look for open doors / night curtain', tool: 'Eyes', minutes: 3, finding: 'Open multideck, curtain rolled up as normal for daytime.' },
    ],
    causes: [
      { id: 'txv', label: 'TXV underfeeding — power element lost its charge', correct: true, why: 'High superheat with a clean coil, no strainer drop, and a bulb that does not move the valve: the valve itself is starving the coil.' },
      { id: 'strainer', label: 'Liquid line strainer plugged', why: 'Same starved signature — but a plugged strainer shows a temperature drop across it. You measured none.' },
      { id: 'charge', label: 'Rack low on charge', why: 'Sight glass is clear and every other case on the line is fine. A rack charge problem does not pick one case.' },
      { id: 'door', label: 'Door left open', why: 'This is an open multideck. An infiltration problem would show LOW superheat from the extra load, not 28 °F.' },
    ],
    fixes: [
      { id: 'txv', label: 'Replace the TXV (or power element), set superheat to 8–10 °F', correct: true, why: 'With a fresh power element the valve opens up, the whole coil frosts evenly, and discharge air settles at 29 °F within the hour.' },
      { id: 'strainer', label: 'Replace the liquid strainer', why: 'It was not restricted. Superheat stays at 28 °F.' },
      { id: 'charge', label: 'Add refrigerant to the rack', why: 'The rack was not low. You have now overcharged a healthy rack and the case is still warm.' },
      { id: 'adjust', label: 'Turn the superheat adjustment out a few turns', why: 'A dead power element cannot be adjusted open — the stem does nothing. Replace it.' },
    ],
    shrinkPerMin: 3,
    complaintAfterMin: 120,
    knowledge: [{ slug: 'sporlan', label: 'Sporlan TXVs' }, { slug: 'refrigeration-fundamentals', label: 'Refrigeration Fundamentals' }],
  },
  {
    id: 'dirty_condenser',
    system: 'refrigeration',
    kinds: ['rack'],
    title: 'High head pressure — Comp 3 tripped on HPCO',
    report: 'Rack controller alarm: HIGH DISCHARGE PRESSURE. Compressor 3 locked out on its high-pressure cutout at 2:10 PM. It is 88 °F outside.',
    cue: 'The rack room is hot. Discharge lines are too hot to touch. Condenser fans on the roof are all running flat out.',
    readings: [
      { key: 'disch', label: 'Discharge pressure', value: 322, unit: 'psig', jitter: 1.2, wander: 2, status: 'crit', expect: '≈ 240 psig at 88 °F ambient (R-404A)' },
      { key: 'sct', label: 'Condensing temp (approx.)', value: 121, unit: '°F', jitter: 0.4, status: 'crit', expect: 'ambient + 15–20 °F' },
      { key: 'amb', label: 'Roof ambient', value: 88, unit: '°F', jitter: 0.2, status: 'ok' },
      { key: 'sc', label: 'Subcooling', value: 4, unit: '°F', jitter: 0.3, status: 'warn', expect: '8–12 °F' },
    ],
    checks: [
      { id: 'roof', label: 'Walk up to the condenser', tool: 'Eyes', minutes: 12, key: true, finding: 'The coil face is matted solid with cottonwood fluff and dust. You cannot see fin through it. Fans are all turning.' },
      { id: 'fans', label: 'Clamp the condenser fan motors', tool: 'Amp clamp', minutes: 8, finding: 'Every fan pulling nameplate amps. Fan control is staging them all on — as it should at this head pressure.' },
      { id: 'sight', label: 'Check the sight glass', tool: 'Eyes', minutes: 4, finding: 'Clear. Receiver level normal.' },
      { id: 'nc', label: 'Compare SCT to ambient with the rack pumped down', tool: 'Gauges', minutes: 20, finding: 'You would need the rack off for this — with fluff on the coil it is not the first thing to try.' },
    ],
    causes: [
      { id: 'dirty', label: 'Dirty / blocked condenser coil', correct: true, why: 'A coil that cannot reject heat pushes SCT far above ambient. Fans running, charge normal, and a coil you cannot see through — this is airflow.' },
      { id: 'over', label: 'Rack overcharged', why: 'Overcharge shows HIGH subcooling as the condenser backs up with liquid. Yours is low, 4 °F.' },
      { id: 'nc', label: 'Non-condensables in the system', why: 'Possible in theory — but you will never know until the coil is clean. Never diagnose air in a system through a dirty coil.' },
      { id: 'fan', label: 'Condenser fan motor failed', why: 'All fans are turning and pulling nameplate amps.' },
    ],
    fixes: [
      { id: 'clean', label: 'Coil cleaner + rinse from the inside out, then reset the HPCO', correct: true, why: 'Head pressure drops to 238 psig in twenty minutes. Comp 3 resets and stays on. Add it to the spring PM list.' },
      { id: 'recover', label: 'Recover refrigerant to bring the head down', why: 'The charge was fine. Now the rack is undercharged AND the coil is still dirty — head pressure comes right back this afternoon.' },
      { id: 'hpco', label: 'Reset the HPCO and raise its setpoint', why: 'Never raise a safety setpoint to make an alarm go away. Comp 3 would trip again — or worse, would not.' },
      { id: 'fanmotor', label: 'Replace a condenser fan motor', why: 'Nothing wrong with the fans.' },
    ],
    shrinkPerMin: 6,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'parallel-rack-systems', label: 'Parallel Rack Systems' }, { slug: 'pressure-switches', label: 'Pressure Switches' }],
  },
  {
    id: 'floodback_bulb',
    system: 'refrigeration',
    kinds: ['walk-in-freezer'],
    title: 'Rack tech says Comp 2 is knocking',
    report: 'LT compressor 2 has been slugging on start-up. The walk-in freezer is the only box on that suction group. Box temp looks fine.',
    cue: 'The box is at temperature. But the suction line out of the evaporator is frosted solid — all the way out through the wall toward the rack.',
    readings: [
      { key: 'box', label: 'Box temperature', value: -9, unit: '°F', jitter: 0.4, wander: 0.8, status: 'ok', expect: '−10 °F' },
      { key: 'suct', label: 'Suction at coil outlet', value: 11.4, unit: 'psig', decimals: 1, jitter: 0.3, status: 'ok', expect: '≈ 10 psig (R-448A)' },
      { key: 'sh', label: 'Superheat', value: 1, unit: '°F', jitter: 0.4, status: 'crit', expect: '6–8 °F' },
      { key: 'll', label: 'Suction line frost', value: 100, unit: '%', jitter: 0, status: 'crit', expect: 'frost ends at the coil' },
    ],
    checks: [
      { id: 'bulb', label: 'Inspect the TXV bulb on the suction line', tool: 'Eyes / hands', minutes: 6, key: true, finding: 'The bulb strap has rusted through. The bulb is dangling in the fan air stream, reading box air instead of the suction line — so the valve thinks the coil is starving and floods it.' },
      { id: 'defrost', label: 'Check the defrost schedule and last cycle', tool: 'Controller', minutes: 6, finding: 'Four defrosts a day, each terminated on temperature. Coil is clean.' },
      { id: 'sight', label: 'Sight glass at the rack', tool: 'Eyes', minutes: 12, finding: 'Clear.' },
      { id: 'door', label: 'Door gasket and closer', tool: 'Hands', minutes: 4, finding: 'Door seals and self-closes. Box holds temp.' },
    ],
    causes: [
      { id: 'bulb', label: 'TXV overfeeding — sensing bulb loose', correct: true, why: 'Superheat at 1 °F with a frosted suction line means liquid is leaving the coil. A bulb that is not on the pipe cannot throttle the valve.' },
      { id: 'charge', label: 'Low charge', why: 'Low charge gives high superheat and a warm box. You have low superheat and a cold box.' },
      { id: 'iced', label: 'Iced coil', why: 'The defrost log is clean and the coil is clear. An iced coil would also pull suction pressure down, not leave it normal.' },
      { id: 'heater', label: 'Defrost heater stuck on', why: 'Heaters on would warm the box and raise suction. Box is at −9 °F.' },
    ],
    fixes: [
      { id: 'strap', label: 'Re-strap the bulb at 10–2 o\'clock on the suction line, insulate, verify superheat', correct: true, why: 'Superheat climbs to 7 °F in ten minutes. Suction frost recedes back to the coil. Comp 2 stops knocking.' },
      { id: 'adjust', label: 'Turn the superheat adjustment in', why: 'You can crank the stem all day — a bulb reading box air will still drive the valve open. Put the bulb on the pipe.' },
      { id: 'txv', label: 'Replace the TXV', why: 'The valve is fine. The new one will flood exactly the same way with the bulb hanging in the air.' },
      { id: 'accum', label: 'Tell the rack tech to add a suction accumulator', why: 'That protects the compressor from the symptom. It does not fix a freezer coil flooding.' },
    ],
    shrinkPerMin: 1,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'sporlan', label: 'Sporlan TXVs' }, { slug: 'walk-in-troubleshooting', label: 'Walk-in Troubleshooting' }],
  },
  {
    id: 'door_ajar',
    system: 'refrigeration',
    kinds: ['reach-in-freezer'],
    title: 'One door on the run frosted up',
    report: 'Night crew says door 3 on this run "looks weird" and the product behind it is frosty.',
    cue: 'Door 3 is standing a half-inch open. There is a bag of frozen peas wedged between the frame and the gasket, and the gasket itself has a ridge of ice on it.',
    readings: [
      { key: 'caseT', label: 'Discharge air', value: -4, unit: '°F', jitter: 0.6, wander: 1.2, status: 'warn', expect: '−12 °F' },
      { key: 'suct', label: 'Suction at case', value: 9.2, unit: 'psig', decimals: 1, jitter: 0.25, status: 'ok', expect: '≈ 8.5 psig' },
      { key: 'sh', label: 'Superheat', value: 8, unit: '°F', jitter: 0.4, status: 'ok', expect: '8–10 °F' },
      { key: 'frost', label: 'Coil frost', value: 68, unit: '%', jitter: 0, status: 'warn', expect: '< 30 %' },
    ],
    checks: [
      { id: 'doors', label: 'Walk the doors on the run', tool: 'Eyes / hands', minutes: 3, key: true, finding: 'Door 3 will not latch. A bag of peas is caught in the frame. Gasket on that door is iced, the others are fine.' },
      { id: 'log', label: 'Pull the defrost log', tool: 'Controller', minutes: 8, finding: 'Defrosts running and terminating normally on temperature.' },
      { id: 'dt', label: 'Meter the DT switch', tool: 'Multimeter', minutes: 10, finding: 'Closed on a cold coil — good.' },
    ],
    causes: [
      { id: 'door', label: 'Door held open — infiltration icing the gasket and coil', correct: true, why: 'Refrigeration readings are healthy. The extra humid air from a door that never latches loads the coil with frost between defrosts.' },
      { id: 'dt', label: 'DT switch failed', why: 'Defrost log and switch both check out.' },
      { id: 'charge', label: 'Low charge', why: 'Superheat is 8 °F — the coil is fed properly.' },
      { id: 'fan', label: 'Fan dead', why: 'Discharge air is moving. Fans are fine.' },
    ],
    fixes: [
      { id: 'clear', label: 'Clear the obstruction, thaw the gasket, run a manual defrost, tell the night crew', correct: true, why: 'Door latches, gasket seals, coil clears on the manual defrost. Case is back to −12 °F in 40 minutes.' },
      { id: 'gasket', label: 'Replace the door gasket', why: 'The gasket was fine once thawed. You spent an hour and a part on a bag of peas.' },
      { id: 'dt', label: 'Replace the DT switch', why: 'It was working.' },
      { id: 'charge', label: 'Add refrigerant', why: 'Superheat was already correct. Now it is flooding.' },
    ],
    shrinkPerMin: 2,
    complaintAfterMin: 150,
    knowledge: [{ slug: 'defrost-systems', label: 'Defrost Systems' }],
  },

  // ── Electrical ──────────────────────────────────────────────────────────────
  {
    id: 'fan_shorted',
    system: 'electrical',
    kinds: ['dairy-case', 'meat-case', 'deli-case'],
    title: 'Case breaker keeps tripping',
    report: 'Store reset the case breaker twice this morning. It trips again within a second. Product is warming.',
    cue: 'The case is silent — no fan noise, no air over the product. The breaker in the panel is in the tripped position.',
    readings: [
      { key: 'prod', label: 'Product temperature', value: 43, unit: '°F', jitter: 0.3, wander: 0.5, status: 'crit', expect: '≤ 38 °F' },
      { key: 'fanA', label: 'Fan circuit current', value: 0, unit: 'A', decimals: 1, jitter: 0, status: 'crit', expect: '0.8 A (2 × 0.4 A)' },
      { key: 'v', label: 'Voltage at case (breaker tripped)', value: 0, unit: 'V', jitter: 0, status: 'crit', expect: '120 V' },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'reset', label: 'Reset the breaker and watch', tool: 'Eyes', minutes: 3, finding: 'Trips instantly with a snap — a dead short, not an overload.' },
      { id: 'ohm', label: 'Ohm each fan motor winding to ground', tool: 'Multimeter (Ω)', minutes: 12, key: true, finding: 'Fan #1: open to ground (good). Fan #2: 0.3 Ω winding-to-ground — the winding has burned through to the frame.' },
      { id: 'heater', label: 'Ohm the anti-sweat / heater circuit', tool: 'Multimeter (Ω)', minutes: 8, finding: 'Heaters read normal resistance, no path to ground.' },
      { id: 'harness', label: 'Inspect the harness for chafed insulation', tool: 'Eyes', minutes: 8, finding: 'Harness looks clean. No rub marks.' },
    ],
    causes: [
      { id: 'fan', label: 'Evap fan #2 motor winding shorted to ground', correct: true, why: 'An instant trip is a short. The meter found it: 0.3 Ω to ground on fan #2. Fan #1 and the heaters are clean.' },
      { id: 'breaker', label: 'Weak breaker', why: 'A tired breaker trips slowly under load. This one snaps instantly — and you found a real short with the meter.' },
      { id: 'neutral', label: 'Loose neutral', why: 'A loose neutral causes flicker and odd voltages, not a dead short trip.' },
      { id: 'heater', label: 'Shorted anti-sweat heater', why: 'The heater circuit ohmed clean.' },
    ],
    fixes: [
      { id: 'fan', label: 'Replace fan #2 motor, verify 0.4 A each, reset breaker', correct: true, why: 'Breaker holds. Both fans pull 0.4 A. Case pulls down over the next hour.' },
      { id: 'breaker', label: 'Replace the breaker', why: 'The new breaker trips too. The short is still in the fan.' },
      { id: 'bigger', label: 'Put in a bigger breaker', why: 'Never. You just turned a nuisance trip into a fire.' },
      { id: 'tape', label: 'Tape the harness and reset', why: 'The fault is inside the motor, not the harness. Trips again.' },
    ],
    shrinkPerMin: 3,
    complaintAfterMin: 120,
    loto: true,
    knowledge: [{ slug: 'math-electrical', label: 'Math & Electrical' }, { slug: 'system-diagnostics', label: 'System Diagnostics' }],
  },
  {
    id: 'control_fuse',
    system: 'electrical',
    kinds: ['walk-in-cooler'],
    title: 'Walk-in cooler dead — lights work',
    report: 'Cooler is at 48 °F and climbing. Lights are on but the evaporator is doing nothing.',
    cue: 'Fans are off. No refrigerant hiss. The liquid line solenoid is silent. The thermostat is calling.',
    readings: [
      { key: 'box', label: 'Box temperature', value: 48, unit: '°F', jitter: 0.3, wander: 0.4, status: 'crit', expect: '35 °F' },
      { key: 'v120', label: 'Transformer primary', value: 121, unit: 'V', jitter: 0.5, status: 'ok', expect: '120 V' },
      { key: 'v24', label: 'Transformer secondary', value: 0, unit: 'V', jitter: 0, status: 'crit', expect: '24 V' },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'fuse', label: 'Pull the 3 A control fuse', tool: 'Eyes / multimeter', minutes: 5, key: true, finding: 'Blown. Blackened glass — it went hard, not from age.' },
      { id: 'sol', label: 'Ohm the liquid line solenoid coil', tool: 'Multimeter (Ω)', minutes: 6, key: true, finding: 'Reads 0.4 Ω. A healthy 24 V coil should read tens of ohms — this coil is shorted.' },
      { id: 'tstat', label: 'Check the thermostat contacts', tool: 'Multimeter', minutes: 6, finding: 'Closed and calling for cooling.' },
      { id: 'xfmr', label: 'Ohm the transformer secondary winding', tool: 'Multimeter (Ω)', minutes: 6, finding: 'Winding is intact. The transformer is fine — it just has no fuse.' },
    ],
    causes: [
      { id: 'sol', label: 'Shorted solenoid coil blew the control fuse', correct: true, why: 'A blown fuse is a symptom. A 0.4 Ω coil is the reason it blew — and it will blow the next one.' },
      { id: 'fuse', label: 'Fuse just failed from age', why: 'Fuses that age out go quietly. This one is blackened, and you found a shorted coil downstream of it.' },
      { id: 'xfmr', label: 'Transformer failed', why: 'Primary has 120 V and the secondary winding ohms good. It is the fuse that opened.' },
      { id: 'tstat', label: 'Thermostat failed open', why: 'The thermostat is closed and calling.' },
    ],
    fixes: [
      { id: 'coil', label: 'Replace the solenoid coil, then the fuse, then verify 24 V', correct: true, why: '24 V returns, solenoid clicks open, fans start, box begins pulling down.' },
      { id: 'fuse', label: 'Replace the fuse only', why: 'It blows the moment you power up. The shorted coil is still there.' },
      { id: 'xfmr', label: 'Replace the transformer', why: 'Nothing wrong with it. Still no fuse.' },
      { id: 'jumper', label: 'Jumper the fuse holder to get it running', why: 'Never bypass a fuse. The transformer would burn up next.' },
    ],
    shrinkPerMin: 4,
    complaintAfterMin: 999,
    loto: true,
    knowledge: [{ slug: 'solenoid-valves', label: 'Solenoid Valves' }, { slug: 'walk-in-troubleshooting', label: 'Walk-in Troubleshooting' }],
  },
  {
    id: 'contactor_burned',
    system: 'electrical',
    kinds: ['rack'],
    title: 'Comp 1 chattering and tripping overloads',
    report: 'Rack controller logs six overload trips on compressor 1 today. When it runs, it sounds rough.',
    cue: 'You can hear the contactor buzzing from the door. The compressor 1 section of the panel smells hot.',
    readings: [
      { key: 'l1', label: 'T1 voltage (load side)', value: 240, unit: 'V', jitter: 0.6, status: 'ok', expect: '240 V' },
      { key: 'l2', label: 'T2 voltage (load side)', value: 238, unit: 'V', jitter: 0.6, status: 'ok', expect: '240 V' },
      { key: 'l3', label: 'T3 voltage (load side)', value: 191, unit: 'V', jitter: 2.5, wander: 4, status: 'crit', expect: '240 V' },
      { key: 'amps', label: 'Phase imbalance', value: 18, unit: '%', jitter: 0.8, status: 'crit', expect: '< 2 %' },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'inspect', label: 'Open the contactor and inspect the terminals', tool: 'Eyes', minutes: 6, key: true, finding: 'T3 terminal is charred and the lug is loose. The wire insulation is browned back an inch. Contact tip on that pole is pitted.' },
      { id: 'line', label: 'Check line-side voltage L1-L2-L3', tool: 'Multimeter', minutes: 4, key: true, finding: '240 / 239 / 240 V on the line side. The utility feed is fine — the drop is across the contactor.' },
      { id: 'wind', label: 'Ohm the compressor windings', tool: 'Multimeter (Ω)', minutes: 10, finding: 'All three windings balanced. Compressor is healthy — so far.' },
      { id: 'oil', label: 'Check compressor oil level', tool: 'Eyes', minutes: 3, finding: 'Sight glass half full. Fine.' },
    ],
    causes: [
      { id: 'contactor', label: 'Burned / loose T3 contactor terminal', correct: true, why: 'Good voltage on the line side, 50 V dropped on one pole on the load side: that is resistance in the contactor, and you saw the charred lug.' },
      { id: 'utility', label: 'Utility single-phasing', why: 'The line side reads balanced. The utility is delivering three good phases.' },
      { id: 'winding', label: 'Compressor winding failing', why: 'Windings ohm balanced. Do not condemn a compressor for a contactor problem.' },
      { id: 'oil', label: 'Low oil', why: 'Oil level is fine, and oil does not cause a phase imbalance.' },
    ],
    fixes: [
      { id: 'contactor', label: 'Replace the contactor, cut back and re-terminate the T3 wire, torque to spec', correct: true, why: 'Load side reads 240 / 239 / 240. Imbalance under 1 %. Compressor runs smooth.' },
      { id: 'tighten', label: 'Tighten the T3 lug and reset', why: 'The contact tip is pitted and the lug is heat-damaged. It will loosen and burn again within the week.' },
      { id: 'comp', label: 'Change the compressor', why: 'A $4,000 fix for a $60 contactor. And the new compressor gets fed through the same burned pole.' },
      { id: 'overload', label: 'Raise the overload setting', why: 'The overload was protecting the compressor from the imbalance. Never defeat it.' },
    ],
    shrinkPerMin: 5,
    complaintAfterMin: 999,
    loto: true,
    knowledge: [{ slug: 'math-electrical', label: 'Math & Electrical' }, { slug: 'copeland', label: 'Copeland Compressors' }],
  },
  {
    id: 'contactor_welded',
    system: 'electrical',
    kinds: ['bunker'],
    title: 'Bunker warm — controller shows refrigeration',
    report: 'Frozen department says the bunker is soft. Controller says it is in refrigeration and has been for hours.',
    cue: 'The case is running, fans on — but the air over the product feels wrong, almost warm, and there is a faint hot-metal smell.',
    readings: [
      { key: 'prod', label: 'Product temperature', value: 6, unit: '°F', jitter: 0.4, wander: 0.6, status: 'crit', expect: '≤ −8 °F' },
      { key: 'htr', label: 'Heater circuit current (in refrigeration!)', value: 8.4, unit: 'A', decimals: 1, jitter: 0.1, status: 'crit', expect: '0 A outside defrost' },
      { key: 'suct', label: 'Suction at case', value: 12.8, unit: 'psig', decimals: 1, jitter: 0.3, status: 'warn', expect: '≈ 9.4 psig' },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'clamp', label: 'Clamp the heater feed while the controller says REFRIGERATION', tool: 'Amp clamp', minutes: 5, key: true, finding: '8.4 A on the heater rung with no defrost commanded. Both elements are energized 24/7.' },
      { id: 'coil', label: 'Meter the defrost contactor coil', tool: 'Multimeter', minutes: 5, key: true, finding: '0 V on the coil — the controller is NOT calling for defrost. The contacts are closed anyway.' },
      { id: 'dt', label: 'Meter the DT switch', tool: 'Multimeter', minutes: 8, finding: 'Opens and closes with coil temp. Fine.' },
      { id: 'sh', label: 'Check superheat', tool: 'Gauges', minutes: 8, finding: 'About 9 °F. Refrigeration side is doing its job — it just cannot beat 1,700 W of heater.' },
    ],
    causes: [
      { id: 'welded', label: 'Defrost contactor welded closed', correct: true, why: 'Heater current with no coil voltage means the contacts are mechanically stuck. The heaters fight the coil around the clock.' },
      { id: 'controller', label: 'Controller stuck in defrost', why: 'The controller is not calling — 0 V on the contactor coil. It is the contactor.' },
      { id: 'dt', label: 'DT switch stuck', why: 'The DT switch checked out, and it cannot energize heaters on its own.' },
      { id: 'txv', label: 'TXV flooding', why: 'Superheat is 9 °F. And a TXV does not put 8.4 A on a heater rung.' },
    ],
    fixes: [
      { id: 'contactor', label: 'Replace the defrost contactor, verify 0 A outside defrost', correct: true, why: 'Heater amps drop to zero. Case pulls down to −10 °F over the next two hours. Check the energy bill next month.' },
      { id: 'controller', label: 'Replace the case controller', why: 'The controller was never calling for defrost. Still 8.4 A on the heaters.' },
      { id: 'pry', label: 'Pry the contacts apart and put it back', why: 'Welded contacts re-weld on the next pull-in. You will be back Thursday.' },
      { id: 'disable', label: 'Disconnect the heaters', why: 'Now it never defrosts. The coil is a block of ice by the weekend.' },
    ],
    shrinkPerMin: 4,
    complaintAfterMin: 120,
    loto: true,
    knowledge: [{ slug: 'defrost-systems', label: 'Defrost Systems' }],
  },

  // ── Plumbing ────────────────────────────────────────────────────────────────
  {
    id: 'condensate_clog',
    system: 'plumbing',
    kinds: ['dairy-case', 'deli-case', 'produce-case'],
    title: 'Water on the floor in front of the case',
    report: 'A customer slipped. Floor staff have been mopping in front of this case all morning. Case temps look fine.',
    cue: 'A shallow puddle along the kickplate, and a wet-cone sign. Product temp is fine — this is not a refrigeration problem.',
    readings: [
      { key: 'dis', label: 'Discharge air', value: 30, unit: '°F', jitter: 0.5, status: 'ok', expect: '28–30 °F' },
      { key: 'pan', label: 'Drain pan level', value: 100, unit: '%', jitter: 0, status: 'crit', expect: 'empty between defrosts' },
    ],
    checks: [
      { id: 'under', label: 'Pull the kickplate and look under the case', tool: 'Eyes / flashlight', minutes: 5, key: true, finding: 'Drain pan is brim-full and sheeting over the edge. The drain line outlet is coated in grey slime.' },
      { id: 'pour', label: 'Pour a cup of water down the drain', tool: 'Cup of water', minutes: 3, key: true, finding: 'Backs up immediately. The line is plugged somewhere between the pan and the floor drain.' },
      { id: 'pan', label: 'Inspect the pan for cracks', tool: 'Eyes', minutes: 4, finding: 'Pan is intact. It is overflowing, not leaking.' },
      { id: 'defrost', label: 'Check defrost settings', tool: 'Controller', minutes: 6, finding: 'Normal off-cycle defrost. Not producing more water than usual.' },
    ],
    causes: [
      { id: 'clog', label: 'Condensate drain line plugged with slime', correct: true, why: 'Full pan, water backs up on a test pour, slime at the outlet. Biofilm builds in every case drain that never gets treated.' },
      { id: 'pan', label: 'Cracked drain pan', why: 'The pan is intact — and a cracked pan would not be brim-full.' },
      { id: 'defrost', label: 'Defrost dumping too much water', why: 'Settings are normal. Even a heavy defrost drains fine through a clear line.' },
      { id: 'leak', label: 'Refrigerant line sweating', why: 'Insulated lines, and sweat would not fill a pan to overflowing.' },
    ],
    fixes: [
      { id: 'clear', label: 'Blow out / snake the drain line, flush, drop in pan tablets', correct: true, why: 'Line runs free. Pan empties. Add this run to the quarterly drain-treatment list so it stays that way.' },
      { id: 'pan', label: 'Replace the drain pan', why: 'New pan, same plugged line — full again by tonight.' },
      { id: 'defrost', label: 'Reduce the defrost frequency', why: 'Less water into a plugged line still overflows — and now the coil ices.' },
      { id: 'mop', label: 'Leave a mop bucket under it and move on', why: 'A slip-and-fall claim costs more than every part on your truck.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 45,
    knowledge: [{ slug: 'system-diagnostics', label: 'System Diagnostics' }],
  },
  {
    id: 'frozen_drain',
    system: 'plumbing',
    kinds: ['walk-in-freezer'],
    title: 'Ice mound on the freezer floor',
    report: 'Receiving says there is a mound of ice growing under the evaporator in the walk-in freezer. Somebody is going to slip on a pallet jack.',
    cue: 'A frozen stalagmite under the coil, and the drain pan has a lip of ice on it. The box is at temperature.',
    readings: [
      { key: 'box', label: 'Box temperature', value: -10, unit: '°F', jitter: 0.4, status: 'ok', expect: '−10 °F' },
      { key: 'pan', label: 'Drain pan', value: 100, unit: '% iced', jitter: 0, status: 'crit', expect: 'clear after each defrost' },
    ],
    checks: [
      { id: 'line', label: 'Trace the drain line from the pan to the wall', tool: 'Eyes / hands', minutes: 6, key: true, finding: 'The line runs eight feet inside the box with no heat tape and no insulation. There is a solid ice plug at the trap outside.' },
      { id: 'defrost', label: 'Check defrost duration and termination', tool: 'Controller', minutes: 6, finding: 'Terminates on temperature in ~25 min. Normal.' },
      { id: 'pitch', label: 'Check the drain pitch', tool: 'Level', minutes: 4, finding: 'Pitched correctly — but pitch does not matter once the water freezes in the line.' },
      { id: 'door', label: 'Door gasket', tool: 'Hands', minutes: 3, finding: 'Seals fine.' },
    ],
    causes: [
      { id: 'frozen', label: 'Drain line freezing — no heat tape inside the box', correct: true, why: 'Defrost water hits −10 °F pipe and freezes before it reaches the wall. Every defrost adds a layer.' },
      { id: 'defrost', label: 'Defrost running too long', why: 'Defrost terminates normally on temperature.' },
      { id: 'leak', label: 'Coil leaking refrigerant', why: 'Box is at temp and the "leak" is water ice, not oil.' },
      { id: 'door', label: 'Door gasket letting humid air in', why: 'Gasket seals. And infiltration frosts the coil and door, not the drain pan.' },
    ],
    fixes: [
      { id: 'tape', label: 'Thaw the line, install self-regulating heat tape + insulation, re-check pitch', correct: true, why: 'Next defrost drains clean out of the box. No new ice.' },
      { id: 'chip', label: 'Chip out the ice and leave it', why: 'Back next week with a bigger mound.' },
      { id: 'shorter', label: 'Shorten defrost', why: 'Still freezes in the pipe — and now the coil does not clear.' },
      { id: 'bigger', label: 'Upsize the drain line', why: 'Bigger pipe, bigger ice plug.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'walk-in-troubleshooting', label: 'Walk-in Troubleshooting' }],
  },
  {
    id: 'dry_trap',
    system: 'plumbing',
    kinds: ['floor-drain'],
    title: 'Sewer smell in the deli',
    report: 'Deli staff are complaining about a sewage smell. Customers have noticed. Manager wants it gone before the lunch rush.',
    cue: 'The smell is strongest right at the floor drain between the deli and meat cases. No water on the floor.',
    readings: [
      { key: 'odor', label: 'Odor at the drain', value: 9, unit: '/10', jitter: 0, status: 'crit', expect: 'none' },
    ],
    checks: [
      { id: 'look', label: 'Shine a light into the floor drain', tool: 'Flashlight', minutes: 2, key: true, finding: 'The trap is bone dry. You can see straight down the pipe. Nothing has drained here in weeks — the deli case drains elsewhere.' },
      { id: 'deli', label: 'Check the deli case drain', tool: 'Eyes', minutes: 5, finding: 'Runs to a different floor drain that has water in its trap. Not the source.' },
      { id: 'grease', label: 'Check for a grease backup', tool: 'Eyes', minutes: 4, finding: 'No standing water, no grease. Nothing is backed up.' },
    ],
    causes: [
      { id: 'dry', label: 'Floor drain trap evaporated dry — sewer gas venting into the store', correct: true, why: 'A trap only blocks sewer gas while it holds water. A drain nothing uses dries out in a few weeks in a warm store.' },
      { id: 'grease', label: 'Grease clog backing up', why: 'Nothing is backed up. The drain is empty, not full.' },
      { id: 'break', label: 'Broken sewer line under the slab', why: 'Possible in theory, but the trap is simply dry — fill it first. Do not dig up a slab for a dry trap.' },
      { id: 'case', label: 'Deli case drain leaking', why: 'The deli case drains to a different, wet trap.' },
    ],
    fixes: [
      { id: 'prime', label: 'Prime the trap with water, add mineral oil or a trap guard, log it for weekly priming', correct: true, why: 'Smell is gone in ten minutes. The oil film slows evaporation; the weekly log keeps it from coming back.' },
      { id: 'snake', label: 'Snake the main line', why: 'Nothing is clogged. The smell continues.' },
      { id: 'plumber', label: 'Call a plumber for a camera inspection', why: 'A $400 call to find a dry trap. Fill it first.' },
      { id: 'bleach', label: 'Pour bleach down it', why: 'Bleach evaporates too. The trap is dry again in days and the smell is back.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 30,
  },
  {
    id: 'condensate_pump',
    system: 'plumbing',
    kinds: ['rtu'],
    title: 'Water dripping from the ceiling in grocery',
    report: 'Ceiling tile is sagging in aisle 5 with water dripping onto the shelf. It has not rained in a week.',
    cue: 'On the roof, the RTU condensate pan is full and overflowing the lip into the curb. The pump is silent.',
    readings: [
      { key: 'pan', label: 'RTU condensate pan level', value: 100, unit: '%', jitter: 0, status: 'crit', expect: 'empty' },
      { key: 'pumpA', label: 'Condensate pump current', value: 0, unit: 'A', decimals: 1, jitter: 0, status: 'crit', expect: '0.6 A when running' },
      { key: 'sup', label: 'Supply air', value: 57, unit: '°F', jitter: 0.4, status: 'ok', expect: '55–58 °F' },
    ],
    checks: [
      { id: 'float', label: 'Lift the pump float by hand', tool: 'Hands', minutes: 3, key: true, finding: 'Float is free but the pump does not run. 120 V is present at the pump — the motor is seized.' },
      { id: 'roof', label: 'Inspect the roof membrane and curb', tool: 'Eyes', minutes: 8, finding: 'Roof is dry and the curb seal is intact. The water is coming from the unit, not the sky.' },
      { id: 'duct', label: 'Check the supply duct for sweating', tool: 'Eyes', minutes: 6, finding: 'Duct is insulated and dry.' },
      { id: 'sh', label: 'Check RTU superheat', tool: 'Gauges', minutes: 10, finding: 'Normal. The coil is cooling fine — it is just making condensate with nowhere to go.' },
    ],
    causes: [
      { id: 'pump', label: 'Condensate pump motor failed', correct: true, why: '120 V at the pump, float free, no rotation — the pump is dead and the pan overflowed into the curb and down the drop.' },
      { id: 'roof', label: 'Roof leak', why: 'No rain in a week and the membrane is dry.' },
      { id: 'duct', label: 'Duct sweating', why: 'Duct is insulated and dry.' },
      { id: 'leak', label: 'Refrigerant leak', why: 'Superheat is normal. And refrigerant does not drip.' },
    ],
    fixes: [
      { id: 'pump', label: 'Replace the condensate pump, clean the pan, verify it cycles', correct: true, why: 'Pump kicks on with a cup of water. Pan is dry. Tell the store to replace the tile.' },
      { id: 'roof', label: 'Patch the roof', why: 'The roof was fine. The pan is still overflowing.' },
      { id: 'float', label: 'Jiggle the float and leave it', why: 'The motor is seized. It was never the float.' },
      { id: 'bypass', label: 'Run a hose off the pan over the roof edge', why: 'Now it drains onto the sidewalk and the customer entrance. And it freezes in winter.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 60,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }],
  },

  // ── HVAC ────────────────────────────────────────────────────────────────────
  {
    id: 'economizer_stuck',
    system: 'hvac',
    kinds: ['rtu'],
    title: 'Every freezer door in the store is sweating',
    report: 'Frozen and dairy both called. Every reach-in door is fogged and the case lips are dripping. Refrigeration alarms across the board.',
    cue: 'The sales floor feels like a locker room. On the roof, RTU-1 outside-air damper is wide open on a muggy afternoon.',
    readings: [
      { key: 'rh', label: 'Store relative humidity', value: 68, unit: '%', jitter: 0.6, wander: 1, status: 'crit', expect: '≤ 50 %' },
      { key: 'storeT', label: 'Store temperature', value: 74, unit: '°F', jitter: 0.3, status: 'ok', expect: '72–75 °F' },
      { key: 'oaRH', label: 'Outdoor RH', value: 86, unit: '%', jitter: 0.5, status: 'warn' },
      { key: 'damper', label: 'Economizer damper position', value: 100, unit: '% open', jitter: 0, status: 'crit', expect: 'minimum position (~15 %) on a humid day' },
    ],
    checks: [
      { id: 'damper', label: 'Inspect the economizer actuator', tool: 'Eyes / hands', minutes: 10, key: true, finding: 'Actuator is not responding to the controller — the damper is mechanically stuck full open. It is dumping 86 % RH outdoor air straight into the store.' },
      { id: 'comp', label: 'Check RTU compressors', tool: 'Eyes / clamp', minutes: 6, finding: 'Both stages running, normal amps. The unit is cooling — it cannot keep up with the moisture load.' },
      { id: 'doors', label: 'Check the front doors', tool: 'Eyes', minutes: 4, finding: 'Doors close and the vestibule is normal.' },
      { id: 'cases', label: 'Check a case superheat', tool: 'Gauges', minutes: 10, finding: 'Normal. The cases are fine — they are just fighting the store air.' },
    ],
    causes: [
      { id: 'econ', label: 'Economizer damper stuck open — flooding the store with humid outside air', correct: true, why: 'Store temp is held, humidity is not. A wide-open damper on a humid day is a moisture pump the RTU cannot outrun.' },
      { id: 'charge', label: 'RTU undercharged', why: 'Compressors are running with normal amps and the store temperature is fine. This is latent load, not capacity.' },
      { id: 'cases', label: 'Case refrigeration fault', why: 'Every case in the store at once is never a case fault. Look at what they share: the air.' },
      { id: 'doors', label: 'Front doors propped open', why: 'Doors check out.' },
    ],
    fixes: [
      { id: 'act', label: 'Replace the actuator, set minimum position, verify high-limit lockout', correct: true, why: 'Damper closes to 15 %. Store RH falls to 52 % over the next three hours and the doors clear.' },
      { id: 'charge', label: 'Add refrigerant to the RTU', why: 'It was not low. RH is still 68 %.' },
      { id: 'defrost', label: 'Add extra defrosts to every case', why: 'Treating the symptom on twenty cases. The doors keep sweating.' },
      { id: 'setpoint', label: 'Drop the store setpoint to 68 °F', why: 'Colder air, same moisture — the doors sweat worse, and the RTU runs harder.' },
    ],
    shrinkPerMin: 3,
    complaintAfterMin: 90,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }, { slug: 'anti-sweat-heaters', label: 'Anti-Sweat Heaters' }],
  },
  {
    id: 'filter_clogged',
    system: 'hvac',
    kinds: ['rtu'],
    title: 'Grocery aisles hot, RTU-2 short cycling',
    report: 'Store temp is 79 °F on the grocery side. Customers are complaining. RTU-2 seems to run for a few minutes and shut off.',
    cue: 'Barely any air from the diffusers. On the roof the unit is loud — the blower is straining against something.',
    readings: [
      { key: 'ret', label: 'Return air', value: 79, unit: '°F', jitter: 0.3, status: 'crit', expect: '72–75 °F' },
      { key: 'sup', label: 'Supply air', value: 49, unit: '°F', jitter: 0.5, status: 'warn', expect: '55–58 °F' },
      { key: 'static', label: 'Total external static', value: 1.4, unit: '"WC', decimals: 2, jitter: 0.02, status: 'crit', expect: '≤ 0.8 "WC' },
      { key: 'lp', label: 'Low-pressure switch trips today', value: 11, unit: '', jitter: 0, status: 'crit', expect: '0' },
    ],
    checks: [
      { id: 'filters', label: 'Pull the filters', tool: 'Hands', minutes: 5, key: true, finding: 'Black, collapsed, and sucked into the rack. Someone skipped the last two PMs.' },
      { id: 'coil', label: 'Inspect the evaporator coil', tool: 'Flashlight', minutes: 6, finding: 'Coil is cold with frost forming at the inlet — starved of airflow, not refrigerant.' },
      { id: 'charge', label: 'Check superheat / subcooling', tool: 'Gauges', minutes: 12, finding: 'Subcooling normal. Superheat low from the lack of load — do not add charge.' },
      { id: 'blower', label: 'Clamp the blower motor', tool: 'Amp clamp', minutes: 5, finding: 'Amps are LOW — the blower is moving very little air.' },
    ],
    causes: [
      { id: 'filter', label: 'Clogged filters — airflow collapsed', correct: true, why: 'High static, low blower amps, very cold supply air, and a low-pressure trip count: the coil is freezing because nothing is moving across it.' },
      { id: 'leak', label: 'Refrigerant leak', why: 'Subcooling is normal and the coil is frosting — it has plenty of refrigerant and no air.' },
      { id: 'comp', label: 'Compressor failing', why: 'Compressor pumps fine when it runs. The low-pressure switch is protecting it from a starved coil.' },
      { id: 'tstat', label: 'Thermostat', why: 'The thermostat is calling. The unit just cannot deliver.' },
    ],
    fixes: [
      { id: 'filters', label: 'Replace filters, let the coil thaw, verify static and a 18–20 °F TD', correct: true, why: 'Static drops to 0.6". Supply air comes up to 56 °F with real airflow. Store pulls down to 74 °F by evening. Put it on the PM schedule.' },
      { id: 'charge', label: 'Add refrigerant', why: 'You just overcharged a unit that had no airflow problem with its charge.' },
      { id: 'comp', label: 'Replace the compressor', why: 'Nothing wrong with the compressor. New one also freezes the coil.' },
      { id: 'bypass', label: 'Jumper the low-pressure switch', why: 'Never. You just removed the one thing keeping the compressor from slugging on a frozen coil.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 60,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }],
  },
  {
    id: 'negative_pressure',
    system: 'hvac',
    kinds: ['entrance'],
    title: 'Front doors slam, cases near the entrance sweating',
    report: 'Front end says the doors have been slamming shut all day and the produce case by the entrance is dripping. Nobody can figure out why.',
    cue: 'Standing in the vestibule you can feel air rushing in past you. The doors fight to close. Warm, humid outside air is pouring across the front cases.',
    readings: [
      { key: 'dp', label: 'Building pressure (ref. outdoors)', value: -0.05, unit: '"WC', decimals: 3, jitter: 0.004, status: 'crit', expect: '+0.02 to +0.05 "WC' },
      { key: 'rh', label: 'RH at the front cases', value: 64, unit: '%', jitter: 0.6, status: 'crit', expect: '≤ 50 %' },
      { key: 'rhBack', label: 'RH at the back of the store', value: 51, unit: '%', jitter: 0.5, status: 'ok' },
    ],
    checks: [
      { id: 'mau', label: 'Check the makeup air unit', tool: 'Eyes / controller', minutes: 12, key: true, finding: 'The makeup air unit is OFF on a tripped belt-break switch. Every exhaust fan is still running — deli hood, restrooms, back room.' },
      { id: 'exhaust', label: 'Check exhaust fans', tool: 'Eyes', minutes: 8, finding: 'Deli hood, restroom, and receiving exhaust all running normally.' },
      { id: 'rtu', label: 'Check RTU outside-air dampers', tool: 'Eyes', minutes: 10, finding: 'At minimum position, working correctly.' },
      { id: 'doors', label: 'Inspect the door closers', tool: 'Hands', minutes: 4, finding: 'Closers are fine. The building is sucking the doors shut.' },
    ],
    causes: [
      { id: 'mau', label: 'Makeup air unit down — exhaust is pulling the building negative', correct: true, why: 'Exhaust out with no makeup air in means the building pulls every cubic foot it needs back through the front doors — hot, wet air straight onto the front cases.' },
      { id: 'closers', label: 'Door closers too strong', why: 'Closers are fine. And closers do not raise the humidity at the produce case.' },
      { id: 'econ', label: 'RTU economizer over-ventilating', why: 'That would push the building POSITIVE. You measured negative.' },
      { id: 'case', label: 'Produce case fault', why: 'The case is fine — it is being hit with 64 % RH air every time the doors open.' },
    ],
    fixes: [
      { id: 'mau', label: 'Replace the belt, reset the break switch, verify positive building pressure', correct: true, why: 'Building comes up to +0.03 "WC. Doors close softly. Front-case RH drops to 52 % within the hour.' },
      { id: 'closers', label: 'Adjust the door closers', why: 'The doors still slam and the case still sweats.' },
      { id: 'exhaust', label: 'Shut off the deli hood exhaust', why: 'Now the deli fills with smoke and the health inspector has a question. Fix the makeup air.' },
      { id: 'defrost', label: 'Add defrosts to the produce case', why: 'Treating the symptom. The building is still negative.' },
    ],
    shrinkPerMin: 1,
    complaintAfterMin: 60,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }],
  },
]

export const FAULT_BY_ID: Record<string, FaultDef> = Object.fromEntries(FAULTS.map(f => [f.id, f]))
