import type { FaultDef, SystemKey } from './types'

export const SYSTEM_META: Record<SystemKey, { label: string; short: string }> = {
  refrigeration: { label: 'Refrigeration', short: 'REF' },
  electrical:    { label: 'Electrical',    short: 'ELEC' },
  plumbing:      { label: 'Plumbing',      short: 'PLMB' },
  hvac:          { label: 'HVAC',          short: 'HVAC' },
}

const LOTO_CHECK = { id: 'loto', label: 'Lock out / tag out the circuit', tool: 'Lock & tag', minutes: 5, finding: 'Breaker locked open, tag hung, verified dead with the meter. Safe to open the panel.' }

export const FAULTS: FaultDef[] = [
  // ── Refrigeration ──────────────────────────────────────────────────────────
  {
    id: 'dt_failed_open',
    system: 'refrigeration',
    kinds: ['reach-in-freezer'],
    title: 'Doors fogged, product going soft',
    report: 'Frozen department says the doors on this run have been sweating since yesterday and the ice cream is soft on the top shelf.',
    cue: 'Every door on the run is fogged. Through the glass you can see frost bridged across the whole coil face. Fans are running hard.',
    readings: [
      { key: 'caseT', label: 'Discharge air', value: 4, unit: '°F', jitter: 0.6, wander: 1, status: 'crit', expect: '−12 °F', after: -12 },
      { key: 'suct', label: 'Suction at case', value: 6.1, unit: 'psig', decimals: 1, jitter: 0.25, wander: 0.4, status: 'warn', expect: '≈ 8.5 psig (−22 °F SST, R-448A)', after: 8.4 },
      { key: 'sh', label: 'Superheat', value: 3, unit: '°F', jitter: 0.4, status: 'warn', expect: '8–10 °F', after: 9 },
      { key: 'frost', label: 'Coil frost', value: 92, unit: '%', jitter: 0, status: 'crit', expect: '< 30 %', after: 12 },
    ],
    checks: [
      { id: 'log', label: 'Pull the controller defrost log', tool: 'Case controller', minutes: 8, key: true, finding: 'Defrost initiated on schedule every 6 h all week. Every cycle logs a termination 40–55 seconds after it started.' },
      { id: 'dt', label: 'Meter the DT switch with the coil cold', tool: 'Multimeter (Ω)', minutes: 10, key: true, finding: 'Coil is at −5 °F. Across the switch terminals: OPEN. The body is stamped OPEN 55 °F / CLOSE 30 °F.' },
      { id: 'sight', label: 'Check the sight glass at the rack', tool: 'Eyes', minutes: 12, finding: 'Clear, no bubbles.' },
      { id: 'gasket', label: 'Walk the door gaskets', tool: 'Hands', minutes: 6, finding: 'A dollar bill drags on every door. No ice on any gasket face.' },
    ],
    causes: [
      { id: 'dt', label: 'Defrost termination switch failed open', correct: true, why: 'The log shows defrost starting and instantly ending; an open DT tells the controller "coil is warm, stop" the moment defrost begins. No melt, ice builds all week.' },
      { id: 'charge', label: 'Low refrigerant charge', why: 'A low charge gives you HIGH superheat and a starved coil. This coil has low superheat and a clear sight glass — it is choked with ice, not starved.' },
      { id: 'gasket', label: 'Door gasket leaking', why: 'Bad gaskets add load and frost, but would not make defrost terminate in under a minute. The log rules this out.' },
      { id: 'fan', label: 'Evaporator fan motor failed', why: 'Fans are audibly running and pulling air. A dead fan would show as no discharge air, not a fogged coil with airflow.' },
    ],
    fixes: [
      { id: 'dt', label: 'Replace the DT switch, force a manual defrost, verify termination on temp', correct: true, cost: 45, why: 'New switch reads closed on a cold coil, opens near 55 °F. Manual defrost clears the coil in ~35 min and the case pulls back to −12 °F.' },
      { id: 'charge', label: 'Add refrigerant', cost: 180, why: 'Nothing is wrong with the charge. You would overcharge the circuit and the coil would still be a block of ice.' },
      { id: 'timer', label: 'Shorten the defrost interval to every 4 h', why: 'More defrosts that each end in a minute still melt nothing. You have to fix why it terminates.' },
      { id: 'scrape', label: 'Scrape the ice off and leave it', why: 'It will be iced again by tomorrow. The termination switch is still open.' },
    ],
    shrinkPerMin: 4,
    complaintAfterMin: 90,
    knowledge: [{ slug: 'defrost-systems', label: 'Defrost Systems' }, { slug: 'system-diagnostics', label: 'System Diagnostics' }],
  },
  {
    id: 'txv_starved',
    system: 'refrigeration',
    kinds: ['dairy-case', 'meat-case'],
    title: 'Case warm, milk at 44 °F',
    report: 'Manager pulled a thermometer on the milk — 44 °F. The rest of the dairy line is fine.',
    cue: 'Fans are strong and the coil is clean, but only the first pass or so is frosted. The rest of the coil is dry and warm.',
    readings: [
      { key: 'dis', label: 'Discharge air', value: 38, unit: '°F', jitter: 0.5, wander: 0.8, status: 'crit', expect: '28–30 °F', after: 29 },
      { key: 'suct', label: 'Suction at case', value: 44, unit: 'psig', decimals: 1, jitter: 0.4, wander: 0.6, status: 'warn', expect: '≈ 53 psig (+18 °F SST, R-404A)', after: 52.6 },
      { key: 'sh', label: 'Superheat', value: 28, unit: '°F', jitter: 0.6, status: 'crit', expect: '8–10 °F', after: 9 },
      { key: 'liq', label: 'Liquid pressure at rack', value: 195, unit: 'psig', jitter: 0.8, status: 'ok', expect: '≈ 195 psig' },
    ],
    checks: [
      { id: 'strainer', label: 'Feel for a temperature drop across the liquid strainer', tool: 'Hands / IR gun', minutes: 6, key: true, finding: 'Strainer inlet 88 °F, outlet 88 °F.' },
      { id: 'bulb', label: 'Inspect the TXV sensing bulb', tool: 'Eyes', minutes: 5, key: true, finding: 'Bulb is strapped tight to the suction line and insulated; capillary intact. You hold the bulb in your hand for two minutes — suction pressure and superheat do not move.' },
      { id: 'sight', label: 'Check the sight glass at the rack', tool: 'Eyes', minutes: 12, finding: 'Clear and full. The other cases on this line are holding temperature.' },
      { id: 'doors', label: 'Look for open doors / night curtain', tool: 'Eyes', minutes: 3, finding: 'Open multideck, curtain rolled up as normal for daytime.' },
    ],
    causes: [
      { id: 'txv', label: 'TXV underfeeding — power element lost its charge', correct: true, why: 'High superheat with a clean coil, no strainer drop, and a bulb that does not move the valve: the valve itself is starving the coil.' },
      { id: 'strainer', label: 'Liquid line strainer plugged', why: 'Same starved signature — but a plugged strainer shows a temperature drop across it. You measured none.' },
      { id: 'charge', label: 'Rack low on charge', why: 'Sight glass is clear and every other case on the line is fine. A rack charge problem does not pick one case.' },
      { id: 'door', label: 'Door left open', why: 'This is an open multideck. An infiltration problem would show LOW superheat from the extra load, not 28 °F.' },
    ],
    fixes: [
      { id: 'txv', label: 'Replace the TXV (or power element), set superheat to 8–10 °F', correct: true, cost: 165, why: 'With a fresh power element the valve opens up, the whole coil frosts evenly, and discharge air settles at 29 °F within the hour.' },
      { id: 'strainer', label: 'Replace the liquid strainer', cost: 38, why: 'It was not restricted. Superheat stays at 28 °F.' },
      { id: 'charge', label: 'Add refrigerant to the rack', cost: 180, why: 'The rack was not low. You have now overcharged a healthy rack and the case is still warm.' },
      { id: 'adjust', label: 'Turn the superheat adjustment out a few turns', why: 'A dead power element cannot be adjusted open — the stem does nothing. Replace it.' },
    ],
    shrinkPerMin: 3,
    complaintAfterMin: 120,
    knowledge: [{ slug: 'sporlan', label: 'Sporlan TXVs' }, { slug: 'refrigeration-fundamentals', label: 'Refrigeration Fundamentals' }],
  },
  {
    id: 'dirty_condenser',
    system: 'refrigeration',
    kinds: ['rack'],
    title: 'High head pressure — Comp 3 tripped on HPCO',
    report: 'Rack controller alarm: HIGH DISCHARGE PRESSURE. Compressor 3 locked out on its high-pressure cutout at 2:10 PM. It is 88 °F outside.',
    cue: 'The rack room is hot. Discharge lines are too hot to touch. Condenser fans on the roof are all running flat out.',
    readings: [
      { key: 'disch', label: 'Discharge pressure', value: 322, unit: 'psig', jitter: 1.2, wander: 2, status: 'crit', expect: '≈ 240 psig at 88 °F ambient (R-404A)', after: 238 },
      { key: 'sct', label: 'Condensing temp (approx.)', value: 121, unit: '°F', jitter: 0.4, status: 'crit', expect: 'ambient + 15–20 °F', after: 104 },
      { key: 'amb', label: 'Roof ambient', value: 88, unit: '°F', jitter: 0.2, status: 'ok' },
      { key: 'sc', label: 'Subcooling', value: 4, unit: '°F', jitter: 0.3, status: 'warn', expect: '8–12 °F', after: 10 },
    ],
    checks: [
      { id: 'roof', label: 'Walk up to the condenser', tool: 'Eyes', minutes: 12, key: true, finding: 'The coil face is matted solid with cottonwood fluff and dust. You cannot see fin through it. Fans are all turning.' },
      { id: 'fans', label: 'Clamp the condenser fan motors', tool: 'Amp clamp', minutes: 8, finding: 'Every fan turning, each pulling nameplate amps. Fan control has all stages energized.' },
      { id: 'sight', label: 'Check the sight glass', tool: 'Eyes', minutes: 4, finding: 'Clear. Receiver level normal.' },
      { id: 'nc', label: 'Compare SCT to ambient with the rack pumped down', tool: 'Gauges', minutes: 20, finding: 'The rack has to be off and equalized for this reading to mean anything — not something you can do at 2 PM with product on the floor.' },
    ],
    causes: [
      { id: 'dirty', label: 'Dirty / blocked condenser coil', correct: true, why: 'A coil that cannot reject heat pushes SCT far above ambient. Fans running, charge normal, and a coil you cannot see through — this is airflow.' },
      { id: 'over', label: 'Rack overcharged', why: 'Overcharge shows HIGH subcooling as the condenser backs up with liquid. Yours is low, 4 °F.' },
      { id: 'nc', label: 'Non-condensables in the system', why: 'Possible in theory — but you will never know until the coil is clean. Never diagnose air in a system through a dirty coil.' },
      { id: 'fan', label: 'Condenser fan motor failed', why: 'All fans are turning and pulling nameplate amps.' },
    ],
    fixes: [
      { id: 'clean', label: 'Coil cleaner + rinse from the inside out, then reset the HPCO', correct: true, cost: 30, why: 'Head pressure drops to 238 psig in twenty minutes. Comp 3 resets and stays on. Add it to the spring PM list.' },
      { id: 'recover', label: 'Recover refrigerant to bring the head down', why: 'The charge was fine. Now the rack is undercharged AND the coil is still dirty — head pressure comes right back this afternoon.' },
      { id: 'hpco', label: 'Reset the HPCO and raise its setpoint', why: 'Never raise a safety setpoint to make an alarm go away. Comp 3 would trip again — or worse, would not.' },
      { id: 'fanmotor', label: 'Replace a condenser fan motor', cost: 290, why: 'Nothing wrong with the fans.' },
    ],
    shrinkPerMin: 6,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'parallel-rack-systems', label: 'Parallel Rack Systems' }, { slug: 'pressure-switches', label: 'Pressure Switches' }],
  },
  {
    id: 'floodback_bulb',
    system: 'refrigeration',
    kinds: ['walk-in-freezer'],
    title: 'Rack tech says Comp 2 is knocking',
    report: 'LT compressor 2 has been slugging on start-up. The walk-in freezer is the only box on that suction group. Box temp looks fine.',
    cue: 'The box is at temperature. But the suction line out of the evaporator is frosted solid — all the way out through the wall toward the rack.',
    readings: [
      { key: 'box', label: 'Box temperature', value: -9, unit: '°F', jitter: 0.4, wander: 0.8, status: 'ok', expect: '−10 °F' },
      { key: 'suct', label: 'Suction at coil outlet', value: 11.4, unit: 'psig', decimals: 1, jitter: 0.3, status: 'ok', expect: '≈ 10 psig (R-448A)' },
      { key: 'sh', label: 'Superheat', value: 1, unit: '°F', jitter: 0.4, status: 'crit', expect: '6–8 °F', after: 7 },
      { key: 'll', label: 'Suction line frost', value: 100, unit: '%', jitter: 0, status: 'crit', expect: 'frost ends at the coil', after: 10 },
    ],
    checks: [
      { id: 'bulb', label: 'Inspect the TXV bulb on the suction line', tool: 'Eyes / hands', minutes: 6, key: true, finding: 'The bulb strap has rusted through. The bulb is hanging free in the fan air stream, not touching the suction line.' },
      { id: 'defrost', label: 'Check the defrost schedule and last cycle', tool: 'Controller', minutes: 6, finding: 'Four defrosts a day, each terminated on temperature. Coil is clean.' },
      { id: 'sight', label: 'Sight glass at the rack', tool: 'Eyes', minutes: 12, finding: 'Clear.' },
      { id: 'door', label: 'Door gasket and closer', tool: 'Hands', minutes: 4, finding: 'Door seals and self-closes. Box holds temp.' },
    ],
    causes: [
      { id: 'bulb', label: 'TXV overfeeding — sensing bulb loose', correct: true, why: 'Superheat at 1 °F with a frosted suction line means liquid is leaving the coil. A bulb that is not on the pipe cannot throttle the valve.' },
      { id: 'charge', label: 'Low charge', why: 'Low charge gives high superheat and a warm box. You have low superheat and a cold box.' },
      { id: 'iced', label: 'Iced coil', why: 'The defrost log is clean and the coil is clear. An iced coil would also pull suction pressure down, not leave it normal.' },
      { id: 'heater', label: 'Defrost heater stuck on', why: 'Heaters on would warm the box and raise suction. Box is at −9 °F.' },
    ],
    fixes: [
      { id: 'strap', label: 'Re-strap the bulb at 10–2 o\'clock on the suction line, insulate, verify superheat', correct: true, cost: 12, why: 'Superheat climbs to 7 °F in ten minutes. Suction frost recedes back to the coil. Comp 2 stops knocking.' },
      { id: 'adjust', label: 'Turn the superheat adjustment in', why: 'You can crank the stem all day — a bulb reading box air will still drive the valve open. Put the bulb on the pipe.' },
      { id: 'txv', label: 'Replace the TXV', cost: 165, why: 'The valve is fine. The new one will flood exactly the same way with the bulb hanging in the air.' },
      { id: 'accum', label: 'Tell the rack tech to add a suction accumulator', why: 'That protects the compressor from the symptom. It does not fix a freezer coil flooding.' },
    ],
    shrinkPerMin: 1,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'sporlan', label: 'Sporlan TXVs' }, { slug: 'walk-in-troubleshooting', label: 'Walk-in Troubleshooting' }],
  },
  {
    id: 'door_ajar',
    system: 'refrigeration',
    kinds: ['reach-in-freezer'],
    title: 'One door on the run frosted up',
    report: 'Night crew says door 3 on this run "looks weird" and the product behind it is frosty.',
    cue: 'Door 3 is standing a half-inch open. There is a bag of frozen peas wedged between the frame and the gasket, and the gasket itself has a ridge of ice on it.',
    readings: [
      { key: 'caseT', label: 'Discharge air', value: -4, unit: '°F', jitter: 0.6, wander: 1.2, status: 'warn', expect: '−12 °F', after: -12 },
      { key: 'suct', label: 'Suction at case', value: 9.2, unit: 'psig', decimals: 1, jitter: 0.25, status: 'ok', expect: '≈ 8.5 psig' },
      { key: 'sh', label: 'Superheat', value: 8, unit: '°F', jitter: 0.4, status: 'ok', expect: '8–10 °F' },
      { key: 'frost', label: 'Coil frost', value: 68, unit: '%', jitter: 0, status: 'warn', expect: '< 30 %', after: 14 },
    ],
    checks: [
      { id: 'doors', label: 'Walk the doors on the run', tool: 'Eyes / hands', minutes: 3, key: true, finding: 'Door 3 will not latch — a bag of peas is caught in the frame. That door has a ridge of ice along the gasket; the rest are clear.' },
      { id: 'log', label: 'Pull the defrost log', tool: 'Controller', minutes: 8, finding: 'Defrosts running and terminating normally on temperature.' },
      { id: 'dt', label: 'Meter the DT switch', tool: 'Multimeter', minutes: 10, finding: 'Closed on a cold coil — good.' },
    ],
    causes: [
      { id: 'door', label: 'Door held open — infiltration icing the gasket and coil', correct: true, why: 'Refrigeration readings are healthy. The extra humid air from a door that never latches loads the coil with frost between defrosts.' },
      { id: 'dt', label: 'DT switch failed', why: 'Defrost log and switch both check out.' },
      { id: 'charge', label: 'Low charge', why: 'Superheat is 8 °F — the coil is fed properly.' },
      { id: 'fan', label: 'Fan dead', why: 'Discharge air is moving. Fans are fine.' },
    ],
    fixes: [
      { id: 'clear', label: 'Clear the obstruction, thaw the gasket, run a manual defrost, tell the night crew', correct: true, why: 'Door latches, gasket seals, coil clears on the manual defrost. Case is back to −12 °F in 40 minutes.' },
      { id: 'gasket', label: 'Replace the door gasket', cost: 140, why: 'The gasket was fine once thawed. You spent an hour and a part on a bag of peas.' },
      { id: 'dt', label: 'Replace the DT switch', cost: 45, why: 'It was working.' },
      { id: 'charge', label: 'Add refrigerant', cost: 180, why: 'Superheat was already correct. Now it is flooding.' },
    ],
    shrinkPerMin: 2,
    complaintAfterMin: 150,
    knowledge: [{ slug: 'defrost-systems', label: 'Defrost Systems' }],
  },

  // ── Electrical ──────────────────────────────────────────────────────────────
  {
    id: 'fan_shorted',
    system: 'electrical',
    kinds: ['dairy-case', 'meat-case', 'deli-case'],
    title: 'Case breaker keeps tripping',
    report: 'Store reset the case breaker twice this morning. It trips again within a second. Product is warming.',
    cue: 'The case is silent — no fan noise, no air over the product. The breaker in the panel is in the tripped position.',
    readings: [
      { key: 'prod', label: 'Product temperature', value: 43, unit: '°F', jitter: 0.3, wander: 0.5, status: 'crit', expect: '≤ 38 °F', after: 37 },
      { key: 'fanA', label: 'Fan circuit current', value: 0, unit: 'A', decimals: 1, jitter: 0, status: 'crit', expect: '0.8 A (2 × 0.4 A)', after: 0.8 },
      { key: 'v', label: 'Voltage at case (breaker tripped)', value: 0, unit: 'V', jitter: 0, status: 'crit', expect: '120 V', after: 121 },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'reset', label: 'Reset the breaker and watch', tool: 'Eyes', minutes: 3, finding: 'Trips the instant the handle comes up, with a snap. No run time at all.' },
      { id: 'ohm', label: 'Ohm each fan motor winding to ground', tool: 'Multimeter (Ω)', minutes: 12, key: true, finding: 'Fan #1 windings to frame: OL. Fan #2 windings to frame: 0.3 Ω.' },
      { id: 'heater', label: 'Ohm the anti-sweat / heater circuit', tool: 'Multimeter (Ω)', minutes: 8, finding: 'Heater circuit reads 48 Ω, and OL to ground.' },
      { id: 'harness', label: 'Inspect the harness for chafed insulation', tool: 'Eyes', minutes: 8, finding: 'Harness looks clean. No rub marks.' },
    ],
    causes: [
      { id: 'fan', label: 'Evap fan #2 motor winding shorted to ground', correct: true, why: 'An instant trip is a short. The meter found it: 0.3 Ω to ground on fan #2. Fan #1 and the heaters are clean.' },
      { id: 'breaker', label: 'Weak breaker', why: 'A tired breaker trips slowly under load. This one snaps instantly — and you found a real short with the meter.' },
      { id: 'neutral', label: 'Loose neutral', why: 'A loose neutral causes flicker and odd voltages, not a dead short trip.' },
      { id: 'heater', label: 'Shorted anti-sweat heater', why: 'The heater circuit ohmed clean.' },
    ],
    fixes: [
      { id: 'fan', label: 'Replace fan #2 motor, verify 0.4 A each, reset breaker', correct: true, cost: 245, why: 'Breaker holds. Both fans pull 0.4 A. Case pulls down over the next hour.' },
      { id: 'breaker', label: 'Replace the breaker', cost: 85, why: 'The new breaker trips too. The short is still in the fan.' },
      { id: 'bigger', label: 'Put in a bigger breaker', cost: 85, why: 'Never. You just turned a nuisance trip into a fire.' },
      { id: 'tape', label: 'Tape the harness and reset', cost: 6, why: 'The fault is inside the motor, not the harness. Trips again.' },
    ],
    shrinkPerMin: 3,
    complaintAfterMin: 120,
    loto: true,
    knowledge: [{ slug: 'math-electrical', label: 'Math & Electrical' }, { slug: 'system-diagnostics', label: 'System Diagnostics' }],
  },
  {
    id: 'control_fuse',
    system: 'electrical',
    kinds: ['walk-in-cooler'],
    title: 'Walk-in cooler dead — lights work',
    report: 'Cooler is at 48 °F and climbing. Lights are on but the evaporator is doing nothing.',
    cue: 'Fans are off. No refrigerant hiss. The liquid line solenoid is silent. The thermostat is calling.',
    readings: [
      { key: 'box', label: 'Box temperature', value: 48, unit: '°F', jitter: 0.3, wander: 0.4, status: 'crit', expect: '35 °F', after: 35 },
      { key: 'v120', label: 'Transformer primary', value: 121, unit: 'V', jitter: 0.5, status: 'ok', expect: '120 V' },
      { key: 'v24', label: 'Transformer secondary', value: 0, unit: 'V', jitter: 0, status: 'crit', expect: '24 V', after: 24 },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'fuse', label: 'Pull the 3 A control fuse', tool: 'Eyes / multimeter', minutes: 5, key: true, finding: 'Blown, and the glass is blackened.' },
      { id: 'sol', label: 'Ohm the liquid line solenoid coil', tool: 'Multimeter (Ω)', minutes: 6, key: true, finding: 'Reads 0.4 Ω. The coil is stamped 24 V, 20 VA.' },
      { id: 'tstat', label: 'Check the thermostat contacts', tool: 'Multimeter', minutes: 6, finding: 'Closed and calling for cooling.' },
      { id: 'xfmr', label: 'Ohm the transformer secondary winding', tool: 'Multimeter (Ω)', minutes: 6, finding: 'Secondary winding reads 2.8 Ω, not open.' },
    ],
    causes: [
      { id: 'sol', label: 'Shorted solenoid coil blew the control fuse', correct: true, why: 'A blown fuse is a symptom. A 0.4 Ω coil is the reason it blew — and it will blow the next one.' },
      { id: 'fuse', label: 'Fuse just failed from age', why: 'Fuses that age out go quietly. This one is blackened, and you found a shorted coil downstream of it.' },
      { id: 'xfmr', label: 'Transformer failed', why: 'Primary has 120 V and the secondary winding ohms good. It is the fuse that opened.' },
      { id: 'tstat', label: 'Thermostat failed open', why: 'The thermostat is closed and calling.' },
    ],
    fixes: [
      { id: 'coil', label: 'Replace the solenoid coil, then the fuse, then verify 24 V', correct: true, cost: 62, why: '24 V returns, solenoid clicks open, fans start, box begins pulling down.' },
      { id: 'fuse', label: 'Replace the fuse only', cost: 4, why: 'It blows the moment you power up. The shorted coil is still there.' },
      { id: 'xfmr', label: 'Replace the transformer', cost: 95, why: 'Nothing wrong with it. Still no fuse.' },
      { id: 'jumper', label: 'Jumper the fuse holder to get it running', why: 'Never bypass a fuse. The transformer would burn up next.' },
    ],
    shrinkPerMin: 4,
    complaintAfterMin: 999,
    loto: true,
    knowledge: [{ slug: 'solenoid-valves', label: 'Solenoid Valves' }, { slug: 'walk-in-troubleshooting', label: 'Walk-in Troubleshooting' }],
  },
  {
    id: 'contactor_burned',
    system: 'electrical',
    kinds: ['rack'],
    title: 'Comp 1 chattering and tripping overloads',
    report: 'Rack controller logs six overload trips on compressor 1 today. When it runs, it sounds rough.',
    cue: 'You can hear the contactor buzzing from the door. The compressor 1 section of the panel smells hot.',
    readings: [
      { key: 'l1', label: 'T1 voltage (load side)', value: 240, unit: 'V', jitter: 0.6, status: 'ok', expect: '240 V' },
      { key: 'l2', label: 'T2 voltage (load side)', value: 238, unit: 'V', jitter: 0.6, status: 'ok', expect: '240 V' },
      { key: 'l3', label: 'T3 voltage (load side)', value: 191, unit: 'V', jitter: 2.5, wander: 4, status: 'crit', expect: '240 V', after: 240 },
      { key: 'amps', label: 'Phase imbalance', value: 18, unit: '%', jitter: 0.8, status: 'crit', expect: '< 2 %', after: 1 },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'inspect', label: 'Open the contactor and inspect the terminals', tool: 'Eyes', minutes: 6, key: true, finding: 'T3 terminal is charred and the lug is loose. The wire insulation is browned back an inch. Contact tip on that pole is pitted.' },
      { id: 'line', label: 'Check line-side voltage L1-L2-L3', tool: 'Multimeter', minutes: 4, key: true, finding: 'Line side: 240 / 239 / 240 V.' },
      { id: 'wind', label: 'Ohm the compressor windings', tool: 'Multimeter (Ω)', minutes: 10, finding: 'T1-T2 2.4 Ω, T2-T3 2.4 Ω, T1-T3 2.4 Ω. All three to ground: OL.' },
      { id: 'oil', label: 'Check compressor oil level', tool: 'Eyes', minutes: 3, finding: 'Sight glass half full. Fine.' },
    ],
    causes: [
      { id: 'contactor', label: 'Burned / loose T3 contactor terminal', correct: true, why: 'Good voltage on the line side, 50 V dropped on one pole on the load side: that is resistance in the contactor, and you saw the charred lug.' },
      { id: 'utility', label: 'Utility single-phasing', why: 'The line side reads balanced. The utility is delivering three good phases.' },
      { id: 'winding', label: 'Compressor winding failing', why: 'Windings ohm balanced. Do not condemn a compressor for a contactor problem.' },
      { id: 'oil', label: 'Low oil', why: 'Oil level is fine, and oil does not cause a phase imbalance.' },
    ],
    fixes: [
      { id: 'contactor', label: 'Replace the contactor, cut back and re-terminate the T3 wire, torque to spec', correct: true, cost: 110, why: 'Load side reads 240 / 239 / 240. Imbalance under 1 %. Compressor runs smooth.' },
      { id: 'tighten', label: 'Tighten the T3 lug and reset', why: 'The contact tip is pitted and the lug is heat-damaged. It will loosen and burn again within the week.' },
      { id: 'comp', label: 'Change the compressor', cost: 2400, why: 'A $4,000 fix for a $60 contactor. And the new compressor gets fed through the same burned pole.' },
      { id: 'overload', label: 'Raise the overload setting', why: 'The overload was protecting the compressor from the imbalance. Never defeat it.' },
    ],
    shrinkPerMin: 5,
    complaintAfterMin: 999,
    loto: true,
    knowledge: [{ slug: 'math-electrical', label: 'Math & Electrical' }, { slug: 'copeland', label: 'Copeland Compressors' }],
  },
  {
    id: 'contactor_welded',
    system: 'electrical',
    kinds: ['bunker'],
    title: 'Bunker warm — controller shows refrigeration',
    report: 'Frozen department says the bunker is soft. Controller says it is in refrigeration and has been for hours.',
    cue: 'The case is running, fans on — but the air over the product feels wrong, almost warm, and there is a faint hot-metal smell.',
    readings: [
      { key: 'prod', label: 'Product temperature', value: 6, unit: '°F', jitter: 0.4, wander: 0.6, status: 'crit', expect: '≤ −8 °F', after: -10 },
      { key: 'htr', label: 'Heater circuit current (in refrigeration!)', value: 8.4, unit: 'A', decimals: 1, jitter: 0.1, status: 'crit', expect: '0 A outside defrost', after: 0 },
      { key: 'suct', label: 'Suction at case', value: 12.8, unit: 'psig', decimals: 1, jitter: 0.3, status: 'warn', expect: '≈ 9.4 psig', after: 9.5 },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'clamp', label: 'Clamp the heater feed while the controller says REFRIGERATION', tool: 'Amp clamp', minutes: 5, key: true, finding: '8.4 A on the heater feed.' },
      { id: 'coil', label: 'Meter the defrost contactor coil', tool: 'Multimeter', minutes: 5, key: true, finding: '0 V across the defrost contactor coil. The contactor is pulled in.' },
      { id: 'dt', label: 'Meter the DT switch', tool: 'Multimeter', minutes: 8, finding: 'Opens and closes with coil temp. Fine.' },
      { id: 'sh', label: 'Check superheat', tool: 'Gauges', minutes: 8, finding: 'About 9 °F. The coil is frosted evenly and the TXV is feeding it.' },
    ],
    causes: [
      { id: 'welded', label: 'Defrost contactor welded closed', correct: true, why: 'Heater current with no coil voltage means the contacts are mechanically stuck. The heaters fight the coil around the clock.' },
      { id: 'controller', label: 'Controller stuck in defrost', why: 'The controller is not calling — 0 V on the contactor coil. It is the contactor.' },
      { id: 'dt', label: 'DT switch stuck', why: 'The DT switch checked out, and it cannot energize heaters on its own.' },
      { id: 'txv', label: 'TXV flooding', why: 'Superheat is 9 °F. And a TXV does not put 8.4 A on a heater rung.' },
    ],
    fixes: [
      { id: 'contactor', label: 'Replace the defrost contactor, verify 0 A outside defrost', correct: true, cost: 95, why: 'Heater amps drop to zero. Case pulls down to −10 °F over the next two hours. Check the energy bill next month.' },
      { id: 'controller', label: 'Replace the case controller', cost: 380, why: 'The controller was never calling for defrost. Still 8.4 A on the heaters.' },
      { id: 'pry', label: 'Pry the contacts apart and put it back', why: 'Welded contacts re-weld on the next pull-in. You will be back Thursday.' },
      { id: 'disable', label: 'Disconnect the heaters', why: 'Now it never defrosts. The coil is a block of ice by the weekend.' },
    ],
    shrinkPerMin: 4,
    complaintAfterMin: 120,
    loto: true,
    knowledge: [{ slug: 'defrost-systems', label: 'Defrost Systems' }],
  },

  // ── Plumbing ────────────────────────────────────────────────────────────────
  {
    id: 'condensate_clog',
    system: 'plumbing',
    kinds: ['dairy-case', 'deli-case', 'produce-case'],
    title: 'Water on the floor in front of the case',
    report: 'A customer slipped. Floor staff have been mopping in front of this case all morning. Case temps look fine.',
    cue: 'A shallow puddle along the kickplate, and a wet-cone sign. Product temp is fine — this is not a refrigeration problem.',
    readings: [
      { key: 'dis', label: 'Discharge air', value: 30, unit: '°F', jitter: 0.5, status: 'ok', expect: '28–30 °F' },
      { key: 'pan', label: 'Drain pan level', value: 100, unit: '%', jitter: 0, status: 'crit', expect: 'empty between defrosts', after: 0 },
    ],
    checks: [
      { id: 'under', label: 'Pull the kickplate and look under the case', tool: 'Eyes / flashlight', minutes: 5, key: true, finding: 'Drain pan is brim-full and sheeting over the edge. The drain line outlet is coated in grey slime.' },
      { id: 'pour', label: 'Pour a cup of water down the drain', tool: 'Cup of water', minutes: 3, key: true, finding: 'Backs up immediately and comes over the pan lip. Nothing reaches the floor drain.' },
      { id: 'pan', label: 'Inspect the pan for cracks', tool: 'Eyes', minutes: 4, finding: 'No cracks. The water is coming over the lip, not through the pan.' },
      { id: 'defrost', label: 'Check defrost settings', tool: 'Controller', minutes: 6, finding: 'Normal off-cycle defrost. Not producing more water than usual.' },
    ],
    causes: [
      { id: 'clog', label: 'Condensate drain line plugged with slime', correct: true, why: 'Full pan, water backs up on a test pour, slime at the outlet. Biofilm builds in every case drain that never gets treated.' },
      { id: 'pan', label: 'Cracked drain pan', why: 'The pan is intact — and a cracked pan would not be brim-full.' },
      { id: 'defrost', label: 'Defrost dumping too much water', why: 'Settings are normal. Even a heavy defrost drains fine through a clear line.' },
      { id: 'leak', label: 'Refrigerant line sweating', why: 'Insulated lines, and sweat would not fill a pan to overflowing.' },
    ],
    fixes: [
      { id: 'clear', label: 'Blow out / snake the drain line, flush, drop in pan tablets', correct: true, cost: 18, why: 'Line runs free. Pan empties. Add this run to the quarterly drain-treatment list so it stays that way.' },
      { id: 'pan', label: 'Replace the drain pan', cost: 210, why: 'New pan, same plugged line — full again by tonight.' },
      { id: 'defrost', label: 'Reduce the defrost frequency', why: 'Less water into a plugged line still overflows — and now the coil ices.' },
      { id: 'mop', label: 'Leave a mop bucket under it and move on', why: 'A slip-and-fall claim costs more than every part on your truck.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 45,
    knowledge: [{ slug: 'system-diagnostics', label: 'System Diagnostics' }],
  },
  {
    id: 'frozen_drain',
    system: 'plumbing',
    kinds: ['walk-in-freezer'],
    title: 'Ice mound on the freezer floor',
    report: 'Receiving says there is a mound of ice growing under the evaporator in the walk-in freezer. Somebody is going to slip on a pallet jack.',
    cue: 'A frozen stalagmite under the coil, and the drain pan has a lip of ice on it. The box is at temperature.',
    readings: [
      { key: 'box', label: 'Box temperature', value: -10, unit: '°F', jitter: 0.4, status: 'ok', expect: '−10 °F' },
      { key: 'pan', label: 'Drain pan', value: 100, unit: '% iced', jitter: 0, status: 'crit', expect: 'clear after each defrost', after: 0 },
    ],
    checks: [
      { id: 'line', label: 'Trace the drain line from the pan to the wall', tool: 'Eyes / hands', minutes: 6, key: true, finding: 'The line runs eight feet inside the box with no heat tape and no insulation. There is a solid ice plug at the trap outside.' },
      { id: 'defrost', label: 'Check defrost duration and termination', tool: 'Controller', minutes: 6, finding: 'Terminates on temperature in ~25 min. Normal.' },
      { id: 'pitch', label: 'Check the drain pitch', tool: 'Level', minutes: 4, finding: 'A quarter inch per foot, correct.' },
      { id: 'door', label: 'Door gasket', tool: 'Hands', minutes: 3, finding: 'Seals fine.' },
    ],
    causes: [
      { id: 'frozen', label: 'Drain line freezing — no heat tape inside the box', correct: true, why: 'Defrost water hits −10 °F pipe and freezes before it reaches the wall. Every defrost adds a layer.' },
      { id: 'defrost', label: 'Defrost running too long', why: 'Defrost terminates normally on temperature.' },
      { id: 'leak', label: 'Coil leaking refrigerant', why: 'Box is at temp and the "leak" is water ice, not oil.' },
      { id: 'door', label: 'Door gasket letting humid air in', why: 'Gasket seals. And infiltration frosts the coil and door, not the drain pan.' },
    ],
    fixes: [
      { id: 'tape', label: 'Thaw the line, install self-regulating heat tape + insulation, re-check pitch', correct: true, cost: 120, why: 'Next defrost drains clean out of the box. No new ice.' },
      { id: 'chip', label: 'Chip out the ice and leave it', why: 'Back next week with a bigger mound.' },
      { id: 'shorter', label: 'Shorten defrost', why: 'Still freezes in the pipe — and now the coil does not clear.' },
      { id: 'bigger', label: 'Upsize the drain line', cost: 65, why: 'Bigger pipe, bigger ice plug.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'walk-in-troubleshooting', label: 'Walk-in Troubleshooting' }],
  },
  {
    id: 'dry_trap',
    system: 'plumbing',
    kinds: ['floor-drain'],
    title: 'Sewer smell in the deli',
    report: 'Deli staff are complaining about a sewage smell. Customers have noticed. Manager wants it gone before the lunch rush.',
    cue: 'The smell is strongest right at the floor drain between the deli and meat cases. No water on the floor.',
    readings: [
      { key: 'odor', label: 'Odor at the drain', value: 9, unit: '/10', jitter: 0, status: 'crit', expect: 'none', after: 0 },
    ],
    checks: [
      { id: 'look', label: 'Shine a light into the floor drain', tool: 'Flashlight', minutes: 2, key: true, finding: 'Bone dry. You can see straight down the pipe.' },
      { id: 'deli', label: 'Check the deli case drain', tool: 'Eyes', minutes: 5, finding: 'It runs to a different floor drain across the aisle, which has water standing in its trap.' },
      { id: 'grease', label: 'Check for a grease backup', tool: 'Eyes', minutes: 4, finding: 'No standing water, no grease. Nothing is backed up.' },
    ],
    causes: [
      { id: 'dry', label: 'Floor drain trap evaporated dry — sewer gas venting into the store', correct: true, why: 'A trap only blocks sewer gas while it holds water. A drain nothing uses dries out in a few weeks in a warm store.' },
      { id: 'grease', label: 'Grease clog backing up', why: 'Nothing is backed up. The drain is empty, not full.' },
      { id: 'break', label: 'Broken sewer line under the slab', why: 'Possible in theory, but the trap is simply dry — fill it first. Do not dig up a slab for a dry trap.' },
      { id: 'case', label: 'Deli case drain leaking', why: 'The deli case drains to a different, wet trap.' },
    ],
    fixes: [
      { id: 'prime', label: 'Prime the trap with water, add mineral oil or a trap guard, log it for weekly priming', correct: true, cost: 14, why: 'Smell is gone in ten minutes. The oil film slows evaporation; the weekly log keeps it from coming back.' },
      { id: 'snake', label: 'Snake the main line', why: 'Nothing is clogged. The smell continues.' },
      { id: 'plumber', label: 'Call a plumber for a camera inspection', cost: 350, why: 'A $400 call to find a dry trap. Fill it first.' },
      { id: 'bleach', label: 'Pour bleach down it', cost: 5, why: 'Bleach evaporates too. The trap is dry again in days and the smell is back.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 30,
  },
  {
    id: 'condensate_pump',
    system: 'plumbing',
    kinds: ['rtu'],
    title: 'Water dripping from the ceiling in grocery',
    report: 'Ceiling tile is sagging in aisle 5 with water dripping onto the shelf. It has not rained in a week.',
    cue: 'On the roof, the RTU condensate pan is full and overflowing the lip into the curb. The pump is silent.',
    readings: [
      { key: 'pan', label: 'RTU condensate pan level', value: 100, unit: '%', jitter: 0, status: 'crit', expect: 'empty', after: 0 },
      { key: 'pumpA', label: 'Condensate pump current', value: 0, unit: 'A', decimals: 1, jitter: 0, status: 'crit', expect: '0.6 A when running', after: 0.6 },
      { key: 'sup', label: 'Supply air', value: 57, unit: '°F', jitter: 0.4, status: 'ok', expect: '55–58 °F' },
    ],
    checks: [
      { id: 'float', label: 'Lift the pump float by hand', tool: 'Hands', minutes: 3, key: true, finding: 'Float moves freely through its whole travel. 120 V at the pump leads. Nothing turns, and the shaft will not move by hand.' },
      { id: 'roof', label: 'Inspect the roof membrane and curb', tool: 'Eyes', minutes: 8, finding: 'Roof is dry and the curb seal is intact. The water is coming from the unit, not the sky.' },
      { id: 'duct', label: 'Check the supply duct for sweating', tool: 'Eyes', minutes: 6, finding: 'Duct is insulated and dry.' },
      { id: 'sh', label: 'Check RTU superheat', tool: 'Gauges', minutes: 10, finding: 'Superheat 11 °F, subcooling 9 °F, supply air 57 °F.' },
    ],
    causes: [
      { id: 'pump', label: 'Condensate pump motor failed', correct: true, why: '120 V at the pump, float free, no rotation — the pump is dead and the pan overflowed into the curb and down the drop.' },
      { id: 'roof', label: 'Roof leak', why: 'No rain in a week and the membrane is dry.' },
      { id: 'duct', label: 'Duct sweating', why: 'Duct is insulated and dry.' },
      { id: 'leak', label: 'Refrigerant leak', why: 'Superheat is normal. And refrigerant does not drip.' },
    ],
    fixes: [
      { id: 'pump', label: 'Replace the condensate pump, clean the pan, verify it cycles', correct: true, cost: 135, why: 'Pump kicks on with a cup of water. Pan is dry. Tell the store to replace the tile.' },
      { id: 'roof', label: 'Patch the roof', why: 'The roof was fine. The pan is still overflowing.' },
      { id: 'float', label: 'Jiggle the float and leave it', why: 'The motor is seized. It was never the float.' },
      { id: 'bypass', label: 'Run a hose off the pan over the roof edge', cost: 20, why: 'Now it drains onto the sidewalk and the customer entrance. And it freezes in winter.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 60,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }],
  },

  // ── HVAC ────────────────────────────────────────────────────────────────────
  {
    id: 'economizer_stuck',
    system: 'hvac',
    kinds: ['rtu'],
    title: 'Every freezer door in the store is sweating',
    report: 'Frozen and dairy both called. Every reach-in door is fogged and the case lips are dripping. Refrigeration alarms across the board.',
    cue: 'The sales floor feels like a locker room. On the roof, RTU-1 outside-air damper is wide open on a muggy afternoon.',
    readings: [
      { key: 'rh', label: 'Store relative humidity', value: 68, unit: '%', jitter: 0.6, wander: 1, status: 'crit', expect: '≤ 50 %', after: 47 },
      { key: 'storeT', label: 'Store temperature', value: 74, unit: '°F', jitter: 0.3, status: 'ok', expect: '72–75 °F' },
      { key: 'oaRH', label: 'Outdoor RH', value: 86, unit: '%', jitter: 0.5, status: 'warn', after: 86 },
      { key: 'damper', label: 'Economizer damper position', value: 100, unit: '% open', jitter: 0, status: 'crit', expect: 'minimum position (~15 %) on a humid day', after: 15 },
    ],
    checks: [
      { id: 'damper', label: 'Inspect the economizer actuator', tool: 'Eyes / hands', minutes: 10, key: true, finding: 'You drive the actuator from the controller: no movement. The damper blades are wide open and will not shift by hand.' },
      { id: 'comp', label: 'Check RTU compressors', tool: 'Eyes / clamp', minutes: 6, finding: 'Both stages running at nameplate amps. Supply air 55 °F.' },
      { id: 'doors', label: 'Check the front doors', tool: 'Eyes', minutes: 4, finding: 'Doors close and the vestibule is normal.' },
      { id: 'cases', label: 'Check a case superheat', tool: 'Gauges', minutes: 10, finding: 'Superheat 9 °F, discharge air 29 °F. The case itself is running to spec.' },
    ],
    causes: [
      { id: 'econ', label: 'Economizer damper stuck open — flooding the store with humid outside air', correct: true, why: 'Store temp is held, humidity is not. A wide-open damper on a humid day is a moisture pump the RTU cannot outrun.' },
      { id: 'charge', label: 'RTU undercharged', why: 'Compressors are running with normal amps and the store temperature is fine. This is latent load, not capacity.' },
      { id: 'cases', label: 'Case refrigeration fault', why: 'Every case in the store at once is never a case fault. Look at what they share: the air.' },
      { id: 'doors', label: 'Front doors propped open', why: 'Doors check out.' },
    ],
    fixes: [
      { id: 'act', label: 'Replace the actuator, set minimum position, verify high-limit lockout', correct: true, cost: 320, why: 'Damper closes to 15 %. Store RH falls to 52 % over the next three hours and the doors clear.' },
      { id: 'charge', label: 'Add refrigerant to the RTU', cost: 210, why: 'It was not low. RH is still 68 %.' },
      { id: 'defrost', label: 'Add extra defrosts to every case', why: 'Treating the symptom on twenty cases. The doors keep sweating.' },
      { id: 'setpoint', label: 'Drop the store setpoint to 68 °F', why: 'Colder air, same moisture — the doors sweat worse, and the RTU runs harder.' },
    ],
    shrinkPerMin: 3,
    complaintAfterMin: 90,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }, { slug: 'anti-sweat-heaters', label: 'Anti-Sweat Heaters' }],
  },
  {
    id: 'filter_clogged',
    system: 'hvac',
    kinds: ['rtu'],
    title: 'Grocery aisles hot, RTU-2 short cycling',
    report: 'Store temp is 79 °F on the grocery side. Customers are complaining. RTU-2 seems to run for a few minutes and shut off.',
    cue: 'Barely any air from the diffusers. On the roof the unit is loud — the blower is straining against something.',
    readings: [
      { key: 'ret', label: 'Return air', value: 79, unit: '°F', jitter: 0.3, status: 'crit', expect: '72–75 °F', after: 74 },
      { key: 'sup', label: 'Supply air', value: 49, unit: '°F', jitter: 0.5, status: 'warn', expect: '55–58 °F', after: 56 },
      { key: 'static', label: 'Total external static', value: 1.4, unit: '"WC', decimals: 2, jitter: 0.02, status: 'crit', expect: '≤ 0.8 "WC', after: 0.6 },
      { key: 'lp', label: 'Low-pressure switch trips today', value: 11, unit: '', jitter: 0, status: 'crit', expect: '0', after: 0 },
    ],
    checks: [
      { id: 'filters', label: 'Pull the filters', tool: 'Hands', minutes: 5, key: true, finding: 'Black, bowed, and pulled in against the rack. The PM sticker shows the last change 11 months ago.' },
      { id: 'coil', label: 'Inspect the evaporator coil', tool: 'Flashlight', minutes: 6, finding: 'Frost forming across the inlet face of the coil.' },
      { id: 'charge', label: 'Check superheat / subcooling', tool: 'Gauges', minutes: 12, finding: 'Subcooling 9 °F. Superheat 3 °F.' },
      { id: 'blower', label: 'Clamp the blower motor', tool: 'Amp clamp', minutes: 5, finding: 'Blower is turning. 1.9 A against a 3.2 A nameplate.' },
    ],
    causes: [
      { id: 'filter', label: 'Clogged filters — airflow collapsed', correct: true, why: 'High static, low blower amps, very cold supply air, and a low-pressure trip count: the coil is freezing because nothing is moving across it.' },
      { id: 'leak', label: 'Refrigerant leak', why: 'Subcooling is normal and the coil is frosting — it has plenty of refrigerant and no air.' },
      { id: 'comp', label: 'Compressor failing', why: 'Compressor pumps fine when it runs. The low-pressure switch is protecting it from a starved coil.' },
      { id: 'tstat', label: 'Thermostat', why: 'The thermostat is calling. The unit just cannot deliver.' },
    ],
    fixes: [
      { id: 'filters', label: 'Replace filters, let the coil thaw, verify static and a 18–20 °F TD', correct: true, cost: 90, why: 'Static drops to 0.6". Supply air comes up to 56 °F with real airflow. Store pulls down to 74 °F by evening. Put it on the PM schedule.' },
      { id: 'charge', label: 'Add refrigerant', cost: 210, why: 'You just overcharged a unit that had no airflow problem with its charge.' },
      { id: 'comp', label: 'Replace the compressor', cost: 3200, why: 'Nothing wrong with the compressor. New one also freezes the coil.' },
      { id: 'bypass', label: 'Jumper the low-pressure switch', why: 'Never. You just removed the one thing keeping the compressor from slugging on a frozen coil.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 60,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }],
  },
  {
    id: 'negative_pressure',
    system: 'hvac',
    kinds: ['entrance'],
    title: 'Front doors slam, cases near the entrance sweating',
    report: 'Front end says the doors have been slamming shut all day and the produce case by the entrance is dripping. Nobody can figure out why.',
    cue: 'Standing in the vestibule you can feel air rushing in past you. The doors fight to close. Warm, humid outside air is pouring across the front cases.',
    readings: [
      { key: 'dp', label: 'Building pressure (ref. outdoors)', value: -0.05, unit: '"WC', decimals: 3, jitter: 0.004, status: 'crit', expect: '+0.02 to +0.05 "WC', after: 0.03 },
      { key: 'rh', label: 'RH at the front cases', value: 64, unit: '%', jitter: 0.6, status: 'crit', expect: '≤ 50 %', after: 49 },
      { key: 'rhBack', label: 'RH at the back of the store', value: 51, unit: '%', jitter: 0.5, status: 'ok' },
    ],
    checks: [
      { id: 'mau', label: 'Check the makeup air unit', tool: 'Eyes / controller', minutes: 12, key: true, finding: 'The makeup air unit is not running. Its belt-break switch is tripped and the belt is lying in the bottom of the cabinet.' },
      { id: 'exhaust', label: 'Check exhaust fans', tool: 'Eyes', minutes: 8, finding: 'Deli hood, restroom, and receiving exhaust all running normally.' },
      { id: 'rtu', label: 'Check RTU outside-air dampers', tool: 'Eyes', minutes: 10, finding: 'At minimum position, working correctly.' },
      { id: 'doors', label: 'Inspect the door closers', tool: 'Hands', minutes: 4, finding: 'Closers adjust and hold normally. With a door cracked open you can feel air rushing in past it.' },
    ],
    causes: [
      { id: 'mau', label: 'Makeup air unit down — exhaust is pulling the building negative', correct: true, why: 'Exhaust out with no makeup air in means the building pulls every cubic foot it needs back through the front doors — hot, wet air straight onto the front cases.' },
      { id: 'closers', label: 'Door closers too strong', why: 'Closers are fine. And closers do not raise the humidity at the produce case.' },
      { id: 'econ', label: 'RTU economizer over-ventilating', why: 'That would push the building POSITIVE. You measured negative.' },
      { id: 'case', label: 'Produce case fault', why: 'The case is fine — it is being hit with 64 % RH air every time the doors open.' },
    ],
    fixes: [
      { id: 'mau', label: 'Replace the belt, reset the break switch, verify positive building pressure', correct: true, cost: 55, why: 'Building comes up to +0.03 "WC. Doors close softly. Front-case RH drops to 52 % within the hour.' },
      { id: 'closers', label: 'Adjust the door closers', why: 'The doors still slam and the case still sweats.' },
      { id: 'exhaust', label: 'Shut off the deli hood exhaust', why: 'Now the deli fills with smoke and the health inspector has a question. Fix the makeup air.' },
      { id: 'defrost', label: 'Add defrosts to the produce case', why: 'Treating the symptom. The building is still negative.' },
    ],
    shrinkPerMin: 1,
    complaintAfterMin: 60,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }],
  },

  // ── Small commercial (gas station / convenience) ────────────────────────────
  {
    id: 'sc_condenser_clogged',
    system: 'refrigeration',
    kinds: ['reach-in-cooler'],
    title: 'Drinks cooler warm, unit running hot',
    report: 'Clerk says the drinks are not cold and the cooler has been "running all day." Product is at 52 °F.',
    cue: 'Warm air is pouring out of the grille at the bottom of the cabinet. The compressor compartment is hot enough to feel from a foot away.',
    readings: [
      { key: 'cab', label: 'Cabinet temperature', value: 52, unit: '°F', jitter: 0.4, wander: 0.6, status: 'crit', expect: '36–38 °F', after: 37 },
      { key: 'head', label: 'Discharge pressure', value: 385, unit: 'psig', jitter: 1.5, status: 'crit', expect: '≈ 240 psig (R-404A, 75 °F room)', after: 245 },
      { key: 'amps', label: 'Compressor amps', value: 7.8, unit: 'A', decimals: 1, jitter: 0.1, status: 'warn', expect: '5.6 A RLA', after: 5.5 },
    ],
    checks: [
      { id: 'grille', label: 'Pull the front grille and look at the condenser', tool: 'Flashlight', minutes: 4, key: true, finding: 'The coil is a felt blanket of dust and floor lint. You cannot see a single fin. The condenser fan behind it is running.' },
      { id: 'fan', label: 'Check the condenser fan', tool: 'Eyes / clamp', minutes: 4, finding: 'Spinning, pulling nameplate amps.' },
      { id: 'evap', label: 'Inspect the evaporator', tool: 'Flashlight', minutes: 5, finding: 'Clean coil, fans running, no ice.' },
      { id: 'gasket', label: 'Check the door gaskets', tool: 'Hands', minutes: 3, finding: 'Seal fine on all doors.' },
    ],
    causes: [
      { id: 'dirty', label: 'Condenser coil blocked with dust — cannot reject heat', correct: true, why: 'Head pressure this high with a clean evaporator and a running fan is a condenser that cannot breathe. Self-contained units live on the floor; this is the #1 call on them.' },
      { id: 'charge', label: 'Low refrigerant', why: 'Low charge gives LOW head pressure and high superheat. Yours is 385 psig.' },
      { id: 'gasket', label: 'Door gasket leaking', why: 'A gasket leak loads the coil but does not push head pressure to 385 psig.' },
      { id: 'tstat', label: 'Thermostat failed', why: 'The unit is calling and running — the thermostat is doing its job.' },
    ],
    fixes: [
      { id: 'clean', label: 'Brush and vacuum the condenser, verify head pressure and amps drop', correct: true, cost: 25, why: 'Head falls to 245 psig, amps to 5.5 A. Cabinet pulls down to 37 °F in two hours. Tell the store: grille cleaning every month.' },
      { id: 'charge', label: 'Recover refrigerant to lower the head', why: 'Now it is undercharged AND the coil is still plugged. Warm again tomorrow.' },
      { id: 'comp', label: 'Replace the compressor', cost: 1150, why: 'The compressor is fine — it is being cooked by a dirty coil. You would cook the new one too.' },
      { id: 'tstat', label: 'Turn the thermostat colder', why: 'It cannot make what it cannot reject. Still 52 °F.' },
    ],
    shrinkPerMin: 2,
    complaintAfterMin: 120,
    knowledge: [{ slug: 'true-manufacturing', label: 'True Reach-ins' }, { slug: 'system-diagnostics', label: 'System Diagnostics' }],
  },
  {
    id: 'beer_cave_door',
    system: 'refrigeration',
    kinds: ['walk-in-cooler'],
    title: 'Beer cave warm, coil iced',
    report: 'Beer is warm and the cave doors are fogged up. Manager says it started after the weekend rush.',
    cue: 'Door 3 on the cave hangs a half-inch open — the closer arm is snapped and the gasket is shredded along the bottom. Inside, the evaporator is frosted solid.',
    readings: [
      { key: 'box', label: 'Cave temperature', value: 46, unit: '°F', jitter: 0.5, wander: 0.8, status: 'crit', expect: '34–36 °F', after: 35 },
      { key: 'frost', label: 'Coil frost', value: 88, unit: '%', jitter: 0, status: 'crit', expect: 'light frost, clears each off-cycle', after: 10 },
      { key: 'sh', label: 'Superheat', value: 4, unit: '°F', jitter: 0.4, status: 'warn', expect: '8–10 °F', after: 9 },
    ],
    checks: [
      { id: 'doors', label: 'Walk every glass door', tool: 'Eyes / hands', minutes: 4, key: true, finding: 'Door 3 does not close on its own; the closer arm is snapped at the elbow and the bottom gasket is torn through.' },
      { id: 'defrost', label: 'Check the defrost timer', tool: 'Timer', minutes: 5, finding: 'Off-cycle defrost, four times a day, each one terminating normally.' },
      { id: 'sight', label: 'Check the sight glass at the condensing unit', tool: 'Eyes', minutes: 8, finding: 'Clear and full, no flashing.' },
      { id: 'fans', label: 'Check the evaporator fans', tool: 'Eyes', minutes: 3, finding: 'Both running. Very little air coming off the coil face.' },
    ],
    causes: [
      { id: 'door', label: 'Door not closing — infiltration is icing the coil', correct: true, why: 'Charge, fans and defrost are normal. A door that stays open turns the coil into a dehumidifier for the whole store, and off-cycle defrost cannot melt that much.' },
      { id: 'charge', label: 'Low charge', why: 'Sight glass is clear and superheat is low, not high.' },
      { id: 'timer', label: 'Defrost timer failed', why: 'The timer is cycling normally.' },
      { id: 'fan', label: 'Evaporator fan failed', why: 'Both fans are running.' },
    ],
    fixes: [
      { id: 'door', label: 'Replace the closer and gasket, force a defrost, verify the door self-closes', correct: true, cost: 320, why: 'Coil clears in 40 minutes. Cave back to 35 °F by evening. Add a door check to the store walk.' },
      { id: 'defrost', label: 'Add four more defrosts a day', why: 'Now the beer warms up eight times a day and the door still hangs open.' },
      { id: 'charge', label: 'Add refrigerant', cost: 190, why: 'It was not low. Now it floods, and the door is still open.' },
      { id: 'chip', label: 'Chip the ice off and leave', why: 'Iced again by the next rush.' },
    ],
    shrinkPerMin: 2,
    complaintAfterMin: 90,
    knowledge: [{ slug: 'walk-in-troubleshooting', label: 'Walk-in Troubleshooting' }],
  },
  {
    id: 'ice_machine_scale',
    system: 'plumbing',
    kinds: ['ice-machine'],
    title: 'Ice machine slow, ice thin and cloudy',
    report: 'Clerk says the bin is never full anymore and the ice looks "milky." It used to fill overnight.',
    cue: 'The machine is running. The evaporator plate has a white, chalky crust and the ice on it is thin and uneven.',
    readings: [
      { key: 'freeze', label: 'Freeze cycle length', value: 26, unit: 'min', jitter: 0, status: 'crit', expect: '15–18 min', after: 16 },
      { key: 'harvest', label: 'Harvest cycle', value: 4.5, unit: 'min', decimals: 1, jitter: 0, status: 'warn', expect: '1–2 min', after: 1.5 },
      { key: 'water', label: 'Water flow at inlet', value: 40, unit: '%', jitter: 0, status: 'warn', expect: 'full flow', after: 100 },
    ],
    checks: [
      { id: 'plate', label: 'Inspect the evaporator plate', tool: 'Eyes', minutes: 3, key: true, finding: 'White, chalky crust over the whole plate. The ice on it is thin and uneven, and it clings when harvest starts.' },
      { id: 'filter', label: 'Check the water filter date', tool: 'Eyes', minutes: 2, key: true, finding: 'Filter is dated 14 months ago. The manual calls for six. Flow through the inlet is well down.' },
      { id: 'charge', label: 'Check refrigerant superheat', tool: 'Gauges', minutes: 10, finding: 'Suction 22 psig, superheat 8 °F, both steady through the freeze cycle.' },
      { id: 'cond', label: 'Check the condenser', tool: 'Eyes', minutes: 4, finding: 'Fins are reasonably clean, discharge pressure normal for the room.' },
    ],
    causes: [
      { id: 'scale', label: 'Mineral scale on the evaporator — water filter neglected', correct: true, why: 'Scale insulates the plate and makes ice cling. Long freeze, long harvest, cloudy ice, and a filter that should have been changed twice.' },
      { id: 'charge', label: 'Low refrigerant', why: 'Superheat is normal; the refrigeration side is doing its job.' },
      { id: 'cond', label: 'Dirty condenser', why: 'The condenser is clean, and it would not make ice cloudy.' },
      { id: 'valve', label: 'Harvest valve stuck', why: 'Harvest is slow because the ice is glued to scale, not because the valve is stuck.' },
    ],
    fixes: [
      { id: 'descale', label: 'Descale with nickel-safe cleaner, sanitize, replace the water filter, set a 6-month filter schedule', correct: true, cost: 85, why: 'Freeze cycle back to 16 minutes, clear ice, bin full by morning. Put the filter date on the machine.' },
      { id: 'charge', label: 'Add refrigerant', cost: 190, why: 'It was not low. Ice is still cloudy.' },
      { id: 'scrape', label: 'Scrape the scale off with a putty knife', why: 'You just scratched the plate. Scale comes back faster and ice sticks worse.' },
      { id: 'replace', label: 'Condemn the machine', cost: 3600, why: 'A $3,000 answer to a $40 filter and an hour of cleaning.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 120,
    knowledge: [{ slug: 'ice-machines', label: 'Ice Machines' }],
  },
  {
    id: 'cond_fan_capacitor',
    system: 'electrical',
    kinds: ['condensing-unit'],
    title: 'Beer cave tripping — outdoor unit fan not turning',
    report: 'Beer cave keeps going warm, then recovering. Out back, the condensing unit "hums but the fan does not spin," per the manager.',
    cue: 'The condensing unit is hot. The fan blade sits still while the compressor runs — then the whole unit clicks off on the high-pressure switch.',
    readings: [
      { key: 'head', label: 'Discharge pressure', value: 365, unit: 'psig', jitter: 2, status: 'crit', expect: '≈ 250 psig at 82 °F', after: 248 },
      { key: 'fanA', label: 'Condenser fan amps', value: 0, unit: 'A', decimals: 1, jitter: 0, status: 'crit', expect: '1.1 A', after: 1.1 },
      { key: 'fanV', label: 'Voltage at fan motor', value: 238, unit: 'V', jitter: 0.5, status: 'ok', expect: '240 V' },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'spin', label: 'Kill power, spin the blade by hand, restore power', tool: 'Hands', minutes: 4, key: true, finding: 'Blade spins freely by hand, no drag or noise. With power on it sits still and hums; one push on the blade and it catches and runs up to speed.' },
      { id: 'cap', label: 'Test the fan run capacitor', tool: 'Multimeter (µF)', minutes: 5, key: true, finding: 'Nameplate 7.5 µF. Meter reads 0.3 µF. The top of the can is domed.' },
      { id: 'wind', label: 'Ohm the fan motor windings', tool: 'Multimeter (Ω)', minutes: 6, finding: 'Windings read balanced, and OL to the frame.' },
      { id: 'contactor', label: 'Inspect the contactor', tool: 'Eyes', minutes: 4, finding: 'Contacts clean. Compressor and fan both fed.' },
    ],
    causes: [
      { id: 'cap', label: 'Fan run capacitor failed', correct: true, why: 'Voltage at the motor, zero amps, and it runs when you spin-start it: no phase shift from the capacitor. The meter confirmed 0.3 µF.' },
      { id: 'motor', label: 'Fan motor burned out', why: 'The windings ohm fine and it runs once started. A dead motor would not run at all.' },
      { id: 'hpco', label: 'High-pressure switch faulty', why: 'The HPCO is doing exactly what it should — protecting the compressor from 365 psig.' },
      { id: 'charge', label: 'System overcharged', why: 'Head pressure is high because the condenser has no airflow, not because of charge.' },
    ],
    fixes: [
      { id: 'cap', label: 'Replace the capacitor with the same µF and voltage rating, verify fan amps, reset the HPCO', correct: true, cost: 22, why: 'Fan runs at 1.1 A. Head drops to 248 psig. Cave holds temperature.' },
      { id: 'motor', label: 'Replace the fan motor', cost: 340, why: 'You changed a good motor and reused the dead capacitor. Same fault.' },
      { id: 'hpco', label: 'Bypass the high-pressure switch', why: 'Never. You just removed the only thing keeping the compressor alive.' },
      { id: 'recover', label: 'Recover refrigerant to bring the head down', why: 'Undercharged now, and the fan still does not spin.' },
    ],
    shrinkPerMin: 2,
    complaintAfterMin: 999,
    loto: true,
    knowledge: [{ slug: 'math-electrical', label: 'Math & Electrical' }, { slug: 'pressure-switches', label: 'Pressure Switches' }],
  },
  {
    id: 'door_heater_open',
    system: 'electrical',
    kinds: ['reach-in-cooler'],
    title: 'One cooler door fogged and dripping',
    report: 'Middle door on the drinks cooler is sweating so badly it drips on the floor. The other doors are dry. Product temp is fine.',
    cue: 'Door 2 is fogged over; doors 1 and 3 are clear. The frame around door 2 is cold to the touch while the others feel warm.',
    readings: [
      { key: 'cab', label: 'Cabinet temperature', value: 37, unit: '°F', jitter: 0.3, status: 'ok', expect: '36–38 °F' },
      { key: 'frame2', label: 'Door 2 frame temperature', value: 46, unit: '°F', jitter: 0.4, status: 'crit', expect: '≈ 70 °F (heated)', after: 70 },
      { key: 'htrA', label: 'Anti-sweat heater circuit current', value: 1.7, unit: 'A', decimals: 1, jitter: 0.05, status: 'warn', expect: '2.5 A (3 × 0.85 A)', after: 2.5 },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'ohm', label: 'Ohm each door frame heater', tool: 'Multimeter (Ω)', minutes: 8, key: true, finding: 'Door 1: 140 Ω. Door 3: 138 Ω. Door 2: OL.' },
      { id: 'rh', label: 'Read the store humidity', tool: 'Hygrometer', minutes: 3, finding: '52 % RH at the front of the case.' },
      { id: 'gasket', label: 'Check the door 2 gasket', tool: 'Hands', minutes: 3, finding: 'Gasket passes a dollar-bill test. The water is beading on the frame metal, not running off the glass.' },
    ],
    causes: [
      { id: 'heater', label: 'Door 2 anti-sweat frame heater open', correct: true, why: 'One cold, sweating frame among warm ones, one-third of the heater current missing, and an open reading on that door. The heater is the frame\'s only defense against condensation.' },
      { id: 'rh', label: 'Store humidity too high', why: 'RH is normal, and humidity fogs every door equally.' },
      { id: 'gasket', label: 'Door 2 gasket leaking', why: 'Gasket seals — and a gasket leak frosts the coil, it does not chill the frame.' },
      { id: 'cold', label: 'Cabinet running too cold', why: 'Cabinet is at 37 °F, right on target.' },
    ],
    fixes: [
      { id: 'heater', label: 'Replace the door 2 frame heater (or door assembly), verify 2.5 A on the circuit', correct: true, cost: 185, why: 'Frame warms to 70 °F in ten minutes. Fog clears. Circuit reads 2.5 A.' },
      { id: 'warm', label: 'Raise the cabinet setpoint', why: 'Warmer drinks, still one cold frame, still dripping.' },
      { id: 'wipe', label: 'Wipe the door and leave a towel', why: 'Back in an hour. The frame is still 46 °F.' },
      { id: 'gasket', label: 'Replace the gasket', cost: 140, why: 'The gasket was fine. Door still sweats.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 90,
    loto: true,
    knowledge: [{ slug: 'anti-sweat-heaters', label: 'Anti-Sweat Heaters' }],
  },
  {
    id: 'ice_machine_drain',
    system: 'plumbing',
    kinds: ['ice-machine'],
    title: 'Water on the floor under the ice machine',
    report: 'Puddle spreading from under the ice machine toward the fountain. Clerk has been throwing towels at it all morning.',
    cue: 'The bin drain is dripping steadily onto the floor and the puddle has a slick, slimy sheen. The floor drain a few feet away is bone dry.',
    readings: [
      { key: 'bin', label: 'Bin water level', value: 100, unit: '%', jitter: 0, status: 'crit', expect: 'draining freely', after: 0 },
      { key: 'floor', label: 'Puddle', value: 6, unit: 'ft wide', jitter: 0, status: 'crit', expect: 'dry floor', after: 0 },
    ],
    checks: [
      { id: 'line', label: 'Trace the bin drain line', tool: 'Flashlight', minutes: 4, key: true, finding: 'The 3/4" drain hose runs under the machine, kinked flat behind one leg. Where it is not kinked, the bore is coated nearly shut with slime.' },
      { id: 'pour', label: 'Pour water into the bin drain', tool: 'Cup of water', minutes: 2, key: true, finding: 'Backs up and runs out the bin door. Nothing reaches the floor drain.' },
      { id: 'inlet', label: 'Check the water inlet valve', tool: 'Eyes', minutes: 4, finding: 'Shuts off cleanly at the end of the fill. Not overfilling.' },
      { id: 'floordrain', label: 'Check the floor drain', tool: 'Flashlight', minutes: 2, finding: 'Clear, with water standing in the trap. Bone dry all around it.' },
    ],
    causes: [
      { id: 'drain', label: 'Bin drain line kinked and slimed shut', correct: true, why: 'Test water backs up, the hose is crushed and full of biofilm, and the floor drain is dry. The melt water has nowhere to go but the floor.' },
      { id: 'inlet', label: 'Water inlet valve stuck open', why: 'The valve shuts off correctly. This is drain water, not fill water.' },
      { id: 'floordrain', label: 'Floor drain clogged', why: 'The floor drain is clear — it is not getting any water.' },
      { id: 'leak', label: 'Refrigerant line sweating', why: 'Six feet of puddle is not sweat.' },
    ],
    fixes: [
      { id: 'drain', label: 'Replace the drain hose, route it with fall and no kinks, keep the air gap, sanitize', correct: true, cost: 26, why: 'Bin drains freely into the floor drain. Floor dry in an hour.' },
      { id: 'inlet', label: 'Replace the water inlet valve', cost: 95, why: 'Fill still fine, drain still kinked, still a puddle.' },
      { id: 'snake', label: 'Snake the floor drain', why: 'It was clear. The puddle is still growing.' },
      { id: 'towels', label: 'Leave more towels', why: 'The health inspector is due Thursday.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 45,
    knowledge: [{ slug: 'ice-machines', label: 'Ice Machines' }],
  },
  {
    id: 'split_ac_filter',
    system: 'hvac',
    kinds: ['split-ac'],
    title: 'Store hot, AC blowing weak and cold',
    report: 'Store is 81 °F. Clerk says the AC "barely blows" and there is ice on the pipe going into the wall.',
    cue: 'The outdoor unit is running. Inside, the supply register is dribbling very cold air, and the insulated suction line is frosted where it enters the air handler.',
    readings: [
      { key: 'ret', label: 'Return air', value: 81, unit: '°F', jitter: 0.3, status: 'crit', expect: '72–75 °F', after: 74 },
      { key: 'sup', label: 'Supply air', value: 43, unit: '°F', jitter: 0.5, status: 'warn', expect: '55–58 °F', after: 56 },
      { key: 'frost', label: 'Indoor coil frost', value: 80, unit: '%', jitter: 0, status: 'crit', expect: 'none', after: 0 },
      { key: 'blower', label: 'Blower amps', value: 1.9, unit: 'A', decimals: 1, jitter: 0.05, status: 'warn', expect: '3.2 A', after: 3.1 },
    ],
    checks: [
      { id: 'filter', label: 'Pull the return filter', tool: 'Hands', minutes: 3, key: true, finding: 'A 1" pleated filter, black and bowed, pulled halfway into the return.' },
      { id: 'sc', label: 'Check subcooling at the outdoor unit', tool: 'Gauges', minutes: 10, finding: 'Subcooling 10 °F. Superheat 2 °F.' },
      { id: 'outdoor', label: 'Check the outdoor coil and fan', tool: 'Eyes', minutes: 5, finding: 'Clean coil, fan running.' },
      { id: 'tstat', label: 'Check the thermostat', tool: 'Eyes', minutes: 2, finding: 'Set to 72, calling for cool.' },
    ],
    causes: [
      { id: 'filter', label: 'Clogged filter — airflow collapsed, coil froze', correct: true, why: 'Low blower amps, very cold supply air, a frosted coil and a normal charge all say the same thing: nothing is moving across the evaporator.' },
      { id: 'charge', label: 'Low refrigerant', why: 'Subcooling is normal. A frosted coil with a good charge is an airflow problem.' },
      { id: 'blower', label: 'Blower motor failing', why: 'Amps are low because it is starved for air, not because it is dying.' },
      { id: 'comp', label: 'Compressor weak', why: 'The compressor is making a 43 °F supply. It is doing too much, not too little.' },
    ],
    fixes: [
      { id: 'filter', label: 'Replace the filter, let the coil thaw with the blower on, verify an 18–20 °F split', correct: true, cost: 14, why: 'Blower amps up to 3.1 A, supply at 56 °F with real airflow. Store down to 74 °F by evening. Filter on the monthly list.' },
      { id: 'charge', label: 'Add refrigerant', cost: 210, why: 'Overcharged now, coil still frozen.' },
      { id: 'blower', label: 'Replace the blower motor', cost: 420, why: 'New motor, same collapsed filter. Same frost.' },
      { id: 'colder', label: 'Set the thermostat lower', why: 'It is already frozen. Lower does not exist.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 60,
    knowledge: [{ slug: 'rtu-diagnostics', label: 'RTU Diagnostics' }],
  },
  // ── CO2 transcritical ──────────────────────────────────────────────────────
  {
    id: 'co2_hpv_stuck',
    system: 'refrigeration',
    kinds: ['flash-tank'],
    title: 'Every case climbing — MT and LT together',
    report: 'Store called at noon: dairy, deli, meat AND the frozen doors are all losing temperature at the same time. Nothing tripped, everything is running.',
    cue: '96 °F outside and the pack is transcritical. The controller has gas cooler pressure pinned at the top of its range while the flash tank sits well under setpoint. Every compressor is loaded.',
    readings: [
      { key: 'head', label: 'Gas cooler pressure', value: 1462, unit: 'psig', jitter: 6, status: 'crit', expect: '≈ 1250 psig at 96 °F', after: 1252 },
      { key: 'flash', label: 'Flash tank pressure', value: 402, unit: 'psig', jitter: 3, status: 'crit', expect: '531 psig (38 °F sat)', after: 529 },
      { key: 'mtSH', label: 'MT suction superheat', value: 38, unit: '°F', jitter: 0.6, status: 'crit', expect: '12–15 °F', after: 14 },
      { key: 'caseT', label: 'Dairy case air', value: 47, unit: '°F', jitter: 0.4, status: 'crit', expect: '36 °F', after: 36 },
    ],
    checks: [
      { id: 'hpv', label: 'Compare the HPV command with its position feedback', tool: 'Controller', minutes: 6, key: true, finding: 'Controller commanding 46 % open. Position feedback reads 3 %, and has not moved in two hours.' },
      { id: 'level', label: 'Read the flash tank level', tool: 'Level probe / sight glass', minutes: 5, key: true, finding: 'Level probe reads 11 %. The glass is clear vapour with a trace of liquid at the very bottom.' },
      { id: 'gc', label: 'Check gas cooler approach and fans', tool: 'Thermometer / eyes', minutes: 6, finding: 'Outdoor air 96 °F, gas cooler outlet 101 °F. All four fans turning.' },
      { id: 'lt', label: 'Read the LT side', tool: 'Controller', minutes: 4, finding: 'LT suction 158 psig, superheat 31 °F. LT cases are climbing too.' },
      { id: 'bypass', label: 'Check the manual HPV bypass hand valve', tool: 'Eyes', minutes: 3, finding: 'Red-tagged NORMALLY CLOSED, handle across the pipe, and it is closed.' },
    ],
    causes: [
      { id: 'hpv', label: 'High pressure valve stuck closed', correct: true, why: 'The valve commands 46 % and reports 3 %. Nothing passes the high side, so the gas cooler stacks up and the flash tank — and every case fed from it — starves.' },
      { id: 'charge', label: 'System undercharged', why: 'Undercharge pulls the HIGH side down with the flash tank. Gas cooler pressure is pinned at the top of the range, not low.' },
      { id: 'gc', label: 'Gas cooler fouled', why: 'Approach is 5 °F with all four fans turning. The coil is doing its job.' },
      { id: 'fgbv', label: 'Flash gas bypass valve stuck open', why: 'That dumps flash tank pressure into the MT suction — you would see MT suction high, not superheat at 38 °F.' },
    ],
    fixes: [
      { id: 'hpv', label: 'Crack the manual bypass to hold head, then replace the HPV stepper and prove it tracks command', correct: true, cost: 980, why: 'Head settles at 1252 psig, flash tank back to 529 psig, superheat to 14 °F. Cases pull down within the hour. Bypass closed and re-tagged before you leave.' },
      { id: 'charge', label: 'Add CO2 to the system', cost: 240, why: 'You pushed more charge at a valve that is not passing anything. Gas cooler pressure went higher, not lower.' },
      { id: 'gc', label: 'Clean the gas cooler', cost: 30, why: 'A clean coil cleaned again. Approach was already 5 °F.' },
      { id: 'flashset', label: 'Raise the flash tank setpoint so it stops alarming', why: 'You moved the alarm, not the valve. Cases keep climbing and now nothing tells you.' },
    ],
    shrinkPerMin: 6,
    complaintAfterMin: 120,
    knowledge: [{ slug: 'co2-transcritical', label: 'CO2 Transcritical' }, { slug: 'rack-valves-components', label: 'Rack Valves' }],
  },
  {
    id: 'co2_fgbv_closed',
    system: 'refrigeration',
    kinds: ['flash-tank'],
    title: 'Flash tank pressure climbing toward the relief',
    report: 'Controller sent a receiver high-pressure warning twice this morning. Store says the cases are fine but the alarm keeps coming back.',
    cue: 'The flash tank gauge is well above where you normally see it, and the number is still creeping. The relief valve on top of the tank is tagged 690 psig.',
    readings: [
      { key: 'flash', label: 'Flash tank pressure', value: 651, unit: 'psig', jitter: 2, status: 'crit', expect: '531 psig (38 °F sat)', after: 532 },
      { key: 'margin', label: 'Margin to relief lift', value: 39, unit: 'psi', jitter: 1, status: 'crit', expect: '> 100 psi', after: 158 },
      { key: 'head', label: 'Gas cooler pressure', value: 1188, unit: 'psig', jitter: 5, status: 'ok', expect: '≈ 1180 psig at 88 °F' },
      { key: 'mtSuct', label: 'MT suction pressure', value: 421, unit: 'psig', jitter: 2, status: 'ok', expect: '425 psig (23 °F sat)' },
    ],
    checks: [
      { id: 'fgbv', label: 'Compare the flash gas bypass valve command with its feedback', tool: 'Controller', minutes: 6, key: true, finding: 'Controller commanding 38 % open. Feedback reads 0 %. Driving it manually from the controller changes nothing.' },
      { id: 'coil', label: 'Ohm the FGBV stepper coil and check the driver', tool: 'Multimeter (Ω)', minutes: 6, key: true, finding: 'Coil windings read within spec. The driver LED for that valve is dark, and the driver has no 24 V on that output.' },
      { id: 'rv', label: 'Inspect the relief valve and its rupture-disc gauge', tool: 'Eyes', minutes: 4, finding: 'Seal intact, tag reads 690 psig, gauge between disc and valve reads 0. It has not lifted.' },
      { id: 'hpv', label: 'Check the HPV', tool: 'Controller', minutes: 4, finding: 'Commanding 41 %, feedback 41 %. Gas cooler pressure is tracking the control curve.' },
      { id: 'charge', label: 'Check charge and tank level', tool: 'Level probe', minutes: 4, finding: 'Level 58 %, normal for this ambient.' },
    ],
    causes: [
      { id: 'fgbv', label: 'Flash gas bypass valve not opening — dead driver output', correct: true, why: 'The only path out of the top of that tank is the bypass into the MT suction. Command 38 %, feedback 0 %, and no 24 V leaving the driver: the valve never gets told to move.' },
      { id: 'hpv', label: 'High pressure valve stuck open', why: 'That would flood the tank from the high side AND pull gas cooler pressure down. Head is right on the curve.' },
      { id: 'overcharge', label: 'System overcharged', why: 'Level is 58 %, normal for 88 °F. Overcharge shows as level, and it would not zero the valve feedback.' },
      { id: 'rv', label: 'Relief valve leaking by', why: 'A leaking relief lowers tank pressure. This tank is going the other way.' },
    ],
    fixes: [
      { id: 'driver', label: 'Replace the failed valve driver output module, prove the FGBV modulates, watch the tank come down', correct: true, cost: 430, why: 'Valve strokes with command. Tank settles at 532 psig with 158 psi of margin to the relief. Alarm clears and stays clear.' },
      { id: 'vent', label: 'Vent the tank down through a hose to atmosphere', why: 'Never. You just dumped CO2 into an occupied machine room, made dry ice in the hose, and the tank climbs straight back.' },
      { id: 'rvset', label: 'Change the relief valve for a higher setting', cost: 640, why: 'The relief is the last thing between this vessel and the room. You do not raise it to hide a control fault.' },
      { id: 'silence', label: 'Silence the receiver alarm for the weekend', why: 'It has 39 psi to go before the relief lifts, and you turned off the only thing watching it.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'pressure-relief-valves', label: 'Relief Valves' }, { slug: 'co2-transcritical', label: 'CO2 Transcritical' }],
  },
  {
    id: 'co2_gc_fan_bank',
    system: 'electrical',
    kinds: ['gas-cooler'],
    title: 'Head pressure high, pack running flat out on a hot day',
    report: 'Energy report flagged this store — the rack has been running at full load every afternoon this week. Nothing alarming, just expensive.',
    cue: 'Out on the pad the gas cooler is roaring at one end and silent at the other. Two of the four fans are not turning.',
    readings: [
      { key: 'head', label: 'Gas cooler pressure', value: 1500, unit: 'psig', jitter: 5, status: 'crit', expect: '≈ 1250 psig at 96 °F', after: 1254 },
      { key: 'gcOut', label: 'Gas cooler outlet temp', value: 113, unit: '°F', jitter: 0.5, status: 'crit', expect: '≈ 101 °F (5 °F approach)', after: 101 },
      { key: 'mtAmps', label: 'MT compressor amps (each)', value: 35.2, unit: 'A', decimals: 1, jitter: 0.3, status: 'warn', expect: '28 A', after: 28.3 },
      { key: 'oat', label: 'Outdoor air', value: 96, unit: '°F', jitter: 0.4, status: 'ok', expect: '—' },
    ],
    checks: [
      LOTO_CHECK,
      { id: 'count', label: 'Count the fans and feel each motor', tool: 'Eyes / hands', minutes: 4, key: true, finding: 'Fans 1 and 2 turning, cool to the touch. Fans 3 and 4 still. Both blades spin freely by hand.' },
      { id: 'contactor', label: 'Check the fan bank contactors', tool: 'Multimeter (V)', minutes: 7, key: true, finding: 'Bank A contactor pulled in, 480 V on all three legs out. Bank B contactor is not pulled in. 24 V present at its coil terminals, 0.6 A through the coil circuit.' },
      { id: 'coil', label: 'Ohm the Bank B contactor coil', tool: 'Multimeter (Ω)', minutes: 5, finding: 'Coil reads OL. Body is discoloured around the coil block.' },
      { id: 'motors', label: 'Ohm fans 3 and 4', tool: 'Multimeter (Ω)', minutes: 6, finding: 'Both balanced leg to leg, OL to frame.' },
      { id: 'coilface', label: 'Inspect the gas cooler coil face', tool: 'Eyes', minutes: 4, finding: 'Fins straight, light dust, you can see daylight through the whole face.' },
    ],
    causes: [
      { id: 'contactor', label: 'Bank B fan contactor coil open — two fans never energised', correct: true, why: '24 V at the coil terminals, current in the circuit, and the coil ohms OL. The controller is calling for the stage; the contactor cannot answer.' },
      { id: 'motors', label: 'Fan motors 3 and 4 burned out', why: 'Both ohm balanced and clear to frame, and both spin freely. They never got voltage.' },
      { id: 'fouled', label: 'Gas cooler coil fouled', why: 'You can see daylight through the face. Half the fans not turning is what raised the approach.' },
      { id: 'ambient', label: 'Nothing wrong — it is just 96 °F out', why: 'At 96 °F with a clean coil and all four fans, approach is about 5 °F. You are reading 17 °F.' },
    ],
    fixes: [
      { id: 'contactor', label: 'Replace the Bank B contactor, verify both fans start and amp out, watch the approach close', correct: true, cost: 145, why: 'All four fans turning. Gas cooler outlet down to 101 °F, head to 1254 psig, MT amps back to 28.3 A each.' },
      { id: 'motors', label: 'Replace fan motors 3 and 4', cost: 620, why: 'Two good motors on the truck floor and the same dead contactor. Fans still do not turn.' },
      { id: 'clean', label: 'Chemical clean the gas cooler coil', cost: 60, why: 'A clean coil, cleaned. Approach is still 17 °F because half the air is missing.' },
      { id: 'jumper', label: 'Jumper across the Bank B contactor to get the fans running', why: 'Now two fan motors run whenever the disconnect is closed, with no overload and no way for the controller to stage them off. That is how you find out what an unprotected motor sounds like.' },
    ],
    shrinkPerMin: 1,
    complaintAfterMin: 999,
    loto: true,
    knowledge: [{ slug: 'gas-coolers', label: 'Gas Coolers' }, { slug: 'math-electrical', label: 'Math & Electrical' }],
  },
  {
    id: 'co2_intercooler_dry',
    system: 'refrigeration',
    kinds: ['intercooler'],
    title: 'MT discharge temperature alarm on the booster pack',
    report: 'Controller has been alarming MT high discharge temperature since early this morning. Cases are all holding.',
    cue: 'The pack is running and every case is on setpoint, but the MT discharge line is too hot to keep a hand on and the oil in the sight glass looks dark.',
    readings: [
      { key: 'mtDisch', label: 'MT discharge temp', value: 262, unit: '°F', jitter: 1, status: 'crit', expect: '≈ 205 °F transcritical', after: 206 },
      { key: 'icLevel', label: 'Intercooler level', value: 4, unit: '%', jitter: 0.5, status: 'crit', expect: '40–55 %', after: 46 },
      { key: 'ltSH', label: 'LT suction superheat', value: 18, unit: '°F', jitter: 0.5, status: 'warn', expect: '10–14 °F', after: 12 },
      { key: 'mtSH', label: 'MT suction superheat', value: 14, unit: '°F', jitter: 0.5, status: 'ok', expect: '12–15 °F' },
    ],
    checks: [
      { id: 'valve', label: 'Compare the intercooler level valve command with its feedback', tool: 'Controller', minutes: 6, key: true, finding: 'Controller calling the valve 100 % open against a 45 % level setpoint. Feedback reads 0 %. Level has been under 10 % since 04:20.' },
      { id: 'glass', label: 'Look at the intercooler sight glasses', tool: 'Eyes', minutes: 4, key: true, finding: 'Both glasses clear. The vessel shell is warm at the top and warm at the bottom — no liquid line anywhere on it.' },
      { id: 'ltliq', label: 'Check subcooling on the LT liquid feed', tool: 'Thermometer / gauges', minutes: 5, finding: 'LT liquid leaving the intercooler at 41 °F against 38 °F saturated. 3 °F of subcooling.' },
      { id: 'oil', label: 'Check oil level and colour at the MT pack', tool: 'Eyes', minutes: 4, finding: 'Levels mid-glass on all three. The oil is noticeably darker than the sample bottle in the machine room.' },
      { id: 'mtvalves', label: 'Compare MT compressor amps and discharge temps against each other', tool: 'Clamp meter', minutes: 6, finding: 'All three within 0.4 A of each other and all three discharge lines the same temperature.' },
    ],
    causes: [
      { id: 'level', label: 'Intercooler level valve failed closed — vessel dry', correct: true, why: 'Nothing knocks the LT discharge down before it joins the MT suction, so the MT compressors swallow hot gas and discharge hotter still. The LT liquid also lost its subcooling on the way past.' },
      { id: 'valveMT', label: 'MT compressor valve plate failure', why: 'One bad compressor runs hotter than its neighbours. All three are within 0.4 A and the same discharge temperature.' },
      { id: 'head', label: 'High head pressure', why: 'Head is on the curve for the ambient. 262 °F is 57 °F past what this head pressure accounts for.' },
      { id: 'lteev', label: 'LT EEVs starved', why: 'LT superheat is 18 °F because the liquid feed lost its subcooling in the dry vessel — the valves are chasing flash gas, not causing it.' },
    ],
    fixes: [
      { id: 'valve', label: 'Replace the intercooler level valve, refill the vessel, verify level holds and MT discharge drops', correct: true, cost: 760, why: 'Level back to 46 %, LT liquid subcooled again, MT discharge down to 206 °F within twenty minutes. Take an oil sample and log it.' },
      { id: 'alarm', label: 'Raise the MT discharge temperature alarm setpoint', why: 'That alarm is the only thing standing between this pack and cooked oil. Moving it does not cool anything.' },
      { id: 'oil', label: 'Change the oil in the MT pack', cost: 310, why: 'Fresh oil into the same 262 °F discharge. It will look like the old oil by next week.' },
      { id: 'comp', label: 'Replace the MT compressor with the highest discharge temp', cost: 4200, why: 'They are all the same temperature, because the problem is what you are feeding them.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'co2-transcritical', label: 'CO2 Transcritical' }, { slug: 'temprite', label: 'Oil Management' }],
  },
  {
    id: 'co2_standstill',
    system: 'refrigeration',
    kinds: ['co2-rack'],
    title: 'Power was out overnight — rack will not restart',
    report: 'Store lost power for about six hours overnight. Power is back, the lights are on, and the rack will not come up. Manager has product on the floor.',
    cue: 'The machine room door is closed and the ventilation fan is running. Through the window the pack is dark and the strobe over the door is flashing.',
    readings: [
      { key: 'ppm', label: 'Machine room CO2', value: 4600, unit: 'ppm', jitter: 40, status: 'crit', expect: '< 1000 ppm', after: 620 },
      { key: 'standstill', label: 'Standstill pressure', value: 688, unit: 'psig', jitter: 2, status: 'crit', expect: '≤ 500 psig held by the pumpdown unit', after: 498 },
      { key: 'flash', label: 'Flash tank level', value: 21, unit: '%', jitter: 0.6, status: 'warn', expect: '45–60 %', after: 52 },
      { key: 'oat', label: 'Outdoor air', value: 78, unit: '°F', jitter: 0.4, status: 'ok', expect: '—' },
    ],
    checks: [
      { id: 'vent', label: 'Confirm the ventilation is actually moving air before anyone opens the door', tool: 'Eyes / anemometer', minutes: 5, key: true, finding: 'Fan running, damper open, strong draught at the louvre. Panel shows 4,600 ppm and falling about 300 ppm a minute.' },
      { id: 'pumpdown', label: 'Check the standstill pumpdown condensing unit', tool: 'Eyes / meter', minutes: 7, key: true, finding: 'The small condensing unit on the flash tank is fed from panel LP-2, normal store power. It has no supply during an outage. Its run-hour counter shows nothing logged last night.' },
      { id: 'rv', label: 'Inspect the relief valve and the gauge under the rupture disc', tool: 'Eyes', minutes: 5, key: true, finding: 'The gauge between the disc and the valve reads 61 psig, not 0. Frost ring around the vent outlet on the roof.' },
      { id: 'gen', label: 'Check what else is on the emergency circuit', tool: 'Panel schedule', minutes: 5, finding: 'Emergency panel carries the case controllers, the gas detector and the ventilation fan. The pumpdown unit is not on it.' },
      { id: 'leak', label: 'Leak-check the pack once the room is clear', tool: 'CO2 detector', minutes: 8, finding: 'Nothing found at the joints. All the loss came out through the roof vent.' },
    ],
    causes: [
      { id: 'standstill', label: 'Pumpdown unit is not on backup power, so standstill pressure rose to the relief and vented', correct: true, why: 'A CO2 rack sitting still warms up and pushes the whole charge toward its saturation pressure at room temperature. The little condensing unit on the flash tank exists to stop that, and it was dead all night with the rest of the store.' },
      { id: 'leak', label: 'Leak in the machine room piping', why: 'A leak-check after ventilating found nothing at the joints, and the gauge under the rupture disc says the charge left through the relief.' },
      { id: 'detector', label: 'Gas detector out of calibration', why: 'The detector is right — you can see where the charge went, and the roof vent has a frost ring on it.' },
      { id: 'comp', label: 'Compressors failed on the restart', why: 'Nothing has tried to start. The pack is locked out on high standstill pressure, which is the control doing its job.' },
    ],
    fixes: [
      { id: 'standstill', label: 'Ventilate to under 1000 ppm, replace the lifted relief, recharge, restart — then get the pumpdown unit moved onto the emergency panel', correct: true, cost: 1250, why: 'Room at 620 ppm before anyone goes in. New relief, charge back, standstill holding 498 psig. The electrician moves the pumpdown circuit next week and this stops being an annual event.' },
      { id: 'recharge', label: 'Recharge it and start the rack', cost: 890, why: 'You bought the store a week. Next outage you are back here buying another charge and another relief valve.' },
      { id: 'rvset', label: 'Fit a relief valve with a higher setting so it stops venting', cost: 680, why: 'The relief is sized for this vessel. A higher setting means the vessel fails before the valve does.' },
      { id: 'bypass', label: 'Bypass the gas detector so the strobe stops and get to work', why: 'The room was at 4,600 ppm. CO2 is heavier than air and it pools where you kneel to work. That detector is the reason this call has no casualty in it.' },
    ],
    shrinkPerMin: 9,
    complaintAfterMin: 150,
    knowledge: [{ slug: 'co2-transcritical', label: 'CO2 Transcritical' }, { slug: 'standby-power', label: 'Standby Power' }, { slug: 'pressure-relief-valves', label: 'Relief Valves' }],
  },
  {
    id: 'co2_lt_eev_overfeed',
    system: 'refrigeration',
    kinds: ['bunker'],
    title: 'Boosters slugging — something is coming back wet',
    report: 'Night crew says the machine room was banging around 2 AM. Cases are all on temperature; the pack just sounds wrong.',
    cue: 'The LT compressors are noisy and the common suction line into them is frosted well past where insulation ends. The bunker itself is holding −12 °F.',
    readings: [
      { key: 'ltSH', label: 'LT suction superheat', value: 1, unit: '°F', decimals: 1, jitter: 0.3, status: 'crit', expect: '10–14 °F', after: 11 },
      { key: 'ltSuct', label: 'LT suction pressure', value: 204, unit: 'psig', jitter: 2, status: 'warn', expect: '190 psig (−22 °F sat)', after: 191 },
      { key: 'ltAmps', label: 'LT compressor amps (each)', value: 21.4, unit: 'A', decimals: 1, jitter: 0.3, status: 'warn', expect: '17 A', after: 17.2 },
      { key: 'caseT', label: 'Bunker air', value: -12, unit: '°F', jitter: 0.5, status: 'ok', expect: '−12 °F' },
    ],
    checks: [
      { id: 'probe', label: 'Compare the EEV driver superheat against a clamped probe and gauge', tool: 'Thermocouple / gauges', minutes: 8, key: true, finding: 'Driver is reporting 11 °F superheat. Your clamped probe and gauge on the same line read 1 °F.' },
      { id: 'well', label: 'Inspect the suction temperature sensor at the case', tool: 'Eyes / hands', minutes: 5, key: true, finding: 'The sensor has come out of its well and is hanging in the return airstream behind the coil. The strap is still on the pipe, empty.' },
      { id: 'eev', label: 'Read the EEV position', tool: 'Controller', minutes: 4, finding: 'Valve at 94 % and holding there.' },
      { id: 'coil', label: 'Look at the bunker coil', tool: 'Eyes', minutes: 5, finding: 'Even light frost across the whole face, fans moving air, drain clear.' },
      { id: 'level', label: 'Check flash tank level and charge', tool: 'Level probe', minutes: 4, finding: 'Level 54 %. Normal.' },
    ],
    causes: [
      { id: 'probe', label: 'EEV suction sensor out of its well — the driver is reading warm air, not pipe', correct: true, why: 'The driver thinks it has 11 °F of superheat and keeps opening. Your gauge and probe on the same pipe say 1 °F. It is feeding liquid to the boosters because it is being lied to.' },
      { id: 'eev', label: 'EEV stuck open mechanically', why: 'The valve is modulating — it sits at 94 % because that is what the controller asked for with the superheat it thinks it has.' },
      { id: 'ice', label: 'Coil iced over', why: 'An iced coil gives you LOW suction with low superheat and a warming case. Suction is high and the case is on setpoint.' },
      { id: 'over', label: 'System overcharged', why: 'Flash tank level is 54 %. Overcharge does not pick one case circuit to flood.' },
    ],
    fixes: [
      { id: 'probe', label: 'Reseat the sensor in its well with heat-transfer paste, re-strap and insulate, verify the driver reads 10–12 °F', correct: true, cost: 6, why: 'Driver and your probe now agree. Valve backs off to 61 %, superheat settles at 11 °F, suction to 191 psig and the banging stops. A tube of paste and a strap.' },
      { id: 'eev', label: 'Replace the EEV', cost: 540, why: 'New valve, same loose sensor, same wide-open command. Still slugging.' },
      { id: 'driver', label: 'Replace the EEV driver', cost: 380, why: 'The driver was doing exactly what its input told it to. The new one does the same.' },
      { id: 'setpoint', label: 'Raise the superheat setpoint on the driver', why: 'You raised a number the driver measures wrongly. Real superheat barely moves and the boosters keep drinking liquid.' },
    ],
    shrinkPerMin: 0,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'micro-thermo', label: 'EEV Controllers' }, { slug: 'co2-transcritical', label: 'CO2 Transcritical' }],
  },
  {
    id: 'co2_leak_alarm',
    system: 'refrigeration',
    kinds: ['gas-detector'],
    title: 'CO2 alarm in the machine room',
    report: 'Manager called it in an hour ago: the horn and strobe outside the machine room went off, the fans came on by themselves, and nobody has been in since.',
    cue: 'Strobe flashing over a closed door, ventilation fan running hard. The panel at the door reads four figures and the trend line is coming down slowly.',
    readings: [
      { key: 'ppm', label: 'Machine room CO2', value: 4800, unit: 'ppm', jitter: 50, status: 'crit', expect: '< 1000 ppm', after: 580 },
      { key: 'flash', label: 'Flash tank level', value: 29, unit: '%', jitter: 0.6, status: 'crit', expect: '45–60 %', after: 53 },
      { key: 'ltSH', label: 'LT suction superheat', value: 21, unit: '°F', jitter: 0.5, status: 'warn', expect: '10–14 °F', after: 12 },
      { key: 'head', label: 'Gas cooler pressure', value: 1042, unit: 'psig', jitter: 4, status: 'warn', expect: '≈ 1180 psig at 88 °F', after: 1176 },
    ],
    checks: [
      { id: 'trend', label: 'Read the detector trend log at the door before going in', tool: 'Controller', minutes: 5, key: true, finding: 'First alarm 06:14, peak 9,200 ppm at 06:40, holding around 4,800 since the fans came on. The rise was gradual, over about two hours.' },
      { id: 'level', label: 'Pull the flash tank level history', tool: 'Controller', minutes: 5, key: true, finding: 'Level has walked down from 56 % to 29 % over four days. Nobody was watching the trend.' },
      { id: 'leak', label: 'Ventilate below 1000 ppm, then leak-check the pack and headers', tool: 'CO2 detector', minutes: 12, key: true, finding: 'Detector screams at a flare on the LT liquid header where it drops to the bunker circuit. The nut is finger-tight and the flare face is scored.' },
      { id: 'cal', label: 'Check the detector calibration date', tool: 'Eyes', minutes: 3, finding: 'Calibrated four months ago, sticker signed, six-month interval.' },
      { id: 'rv', label: 'Inspect the relief valve', tool: 'Eyes', minutes: 4, finding: 'Seal intact, gauge under the rupture disc reads 0. It has not lifted.' },
    ],
    causes: [
      { id: 'flare', label: 'Leak at a flare on the LT liquid header', correct: true, why: 'Four days of falling level, a gradual ppm rise rather than a dump, and a detector that goes off at one fitting. The relief never lifted, so the charge left through that joint.' },
      { id: 'false', label: 'False alarm — sensor out of calibration', why: 'Calibrated four months ago inside a six-month interval, and the flash tank has genuinely lost a quarter of its level.' },
      { id: 'rv', label: 'Relief valve lifted', why: 'Seal intact and the gauge under the disc reads 0. A lift is a fast dump, not a four-day drift.' },
      { id: 'defrost', label: 'Dry ice from a defrost cycle sublimating', why: 'There is no dry ice in a closed system. And the level history says a quarter of the charge is gone.' },
    ],
    fixes: [
      { id: 'flare', label: 'Ventilate under 1000 ppm, recover that section, cut out and remake the flare, pressure-test, recharge and log the leak', correct: true, cost: 410, why: 'Room at 580 ppm. New flare holds a standing test. Level back to 53 %, LT superheat to 12 °F, head back on the curve. The leak goes on the record with the amount.' },
      { id: 'tighten', label: 'Reach in and tighten the flare nut with the system running', cost: 0, why: 'On a scored flare face, live, at 500 psig, in a room at 4,800 ppm, with liquid CO2 on the other side of that nut. No.' },
      { id: 'sensor', label: 'Replace the gas detector head', cost: 690, why: 'A new head reads the same 4,800 ppm, because the ppm is real.' },
      { id: 'silence', label: 'Silence the alarm, top up the charge, and move on', cost: 890, why: 'You paid for a charge you are about to lose again, and turned off the thing that told you.' },
    ],
    shrinkPerMin: 2,
    complaintAfterMin: 999,
    knowledge: [{ slug: 'co2-transcritical', label: 'CO2 Transcritical' }, { slug: 'commissioning', label: 'Leak Testing' }],
  },
]

export const FAULT_BY_ID: Record<string, FaultDef> = Object.fromEntries(FAULTS.map(f => [f.id, f]))
